#!/bin/bash
# Script de déploiement rapide pour VPS OVH

echo "=== Déploiement rapide sur VPS OVH (51.75.26.4) ==="
echo ""
echo "Ce script va vous aider à déployer rapidement votre site."
echo ""
echo "ÉTAPES À SUIVRE :"
echo ""
echo "1. Connectez-vous à votre VPS :"
echo "   ssh root@51.75.26.4"
echo ""
echo "2. Exécutez ces commandes une par une :"
echo ""
echo "   # Mise à jour du système"
echo "   apt update && apt upgrade -y"
echo ""
echo "   # Installation de Node.js 20"
echo "   curl -fsSL https://deb.nodesource.com/setup_20.x | bash -"
echo "   apt install -y nodejs"
echo ""
echo "   # Installation de PM2 et Git"
echo "   npm install -g pm2"
echo "   apt install -y git nginx"
echo ""
echo "   # Création du répertoire"
echo "   mkdir -p /var/www/rdistrib"
echo "   cd /var/www/rdistrib"
echo ""
echo "   # Clonage du projet"
echo "   git clone https://github.com/nathwebdesign/rdistrib-websitenew.git ."
echo ""
echo "   # Configuration de l'environnement"
echo "   cp .env.production .env.local"
echo "   nano .env.local  # Modifier si nécessaire"
echo ""
echo "   # Installation et build"
echo "   npm install"
echo "   npm run build"
echo ""
echo "   # Configuration Nginx"
echo "   cp deploy/nginx.conf /etc/nginx/sites-available/rdistrib"
echo "   ln -s /etc/nginx/sites-available/rdistrib /etc/nginx/sites-enabled/"
echo "   rm /etc/nginx/sites-enabled/default"
echo "   nginx -t"
echo "   systemctl restart nginx"
echo ""
echo "   # Démarrage avec PM2"
echo "   cp deploy/ecosystem.config.js ."
echo "   pm2 start ecosystem.config.js"
echo "   pm2 save"
echo "   pm2 startup"
echo ""
echo "3. Votre site sera accessible sur http://51.75.26.4"
echo ""
echo "Pour plus de détails, consultez deploy/DEPLOYMENT_GUIDE.md"