// Zones Express Région Parisienne
// Zone A : 0-30 km
// Zone B : 30-50 km  
// Zone C : 50-70 km
// Zone D : 70+ km

export interface VilleExpressRP {
  nom: string;
  codePostal: string;
  zone: 'A' | 'B' | 'C' | 'D';
}

// Liste des villes par zone
export const villesExpressRP: VilleExpressRP[] = [
  // Zone A
  { nom: "ABLON SUR SEINE", codePostal: "94", zone: "A" },
  { nom: "ACHERES", codePostal: "78", zone: "A" },
  { nom: "ADAINVILLE", codePostal: "78", zone: "A" },
  { nom: "AINCOURT", codePostal: "95", zone: "A" },
  { nom: "ALFORTVILLE", codePostal: "94", zone: "A" },
  { nom: "ANDILLY", codePostal: "95", zone: "A" },
  { nom: "ANDRESY", codePostal: "78", zone: "A" },
  { nom: "ANNET SUR MARNE", codePostal: "77", zone: "A" },
  { nom: "ANTONY", codePostal: "92", zone: "A" },
  { nom: "ARCUEIL", codePostal: "94", zone: "A" },
  { nom: "ARGENTEUIL", codePostal: "95", zone: "A" },
  { nom: "ARNOUVILLE", codePostal: "95", zone: "A" },
  { nom: "ARNOUVILLE LES GONESSES", codePostal: "95", zone: "A" },
  { nom: "ARTHIES", codePostal: "95", zone: "A" },
  { nom: "ASNIERES SUR SEINE", codePostal: "92", zone: "A" },
  { nom: "ASNIERS SUR OISE", codePostal: "95", zone: "A" },
  { nom: "ATHIS MONS", codePostal: "91", zone: "A" },
  { nom: "ATTAINVILLE", codePostal: "95", zone: "A" },
  { nom: "AUBERVILLIERS", codePostal: "93", zone: "A" },
  { nom: "AULNAY SOUS BOIS", codePostal: "93", zone: "A" },
  { nom: "BAGNEUX", codePostal: "92", zone: "A" },
  { nom: "BAGNOLET", codePostal: "93", zone: "A" },
  { nom: "BAILLET EN FRANCE", codePostal: "95", zone: "A" },
  { nom: "BALLANCOURT SUR ESSONNE", codePostal: "91", zone: "A" },
  { nom: "BANTHELU", codePostal: "95", zone: "A" },
  { nom: "BEAUCHAMP", codePostal: "95", zone: "A" },
  { nom: "BEAUMONT SUR OISE", codePostal: "95", zone: "A" },
  { nom: "BELLEFONTAINE", codePostal: "95", zone: "A" },
  { nom: "BELLOY EN FRANCE", codePostal: "95", zone: "A" },
  { nom: "BESSANCOURT", codePostal: "95", zone: "A" },
  { nom: "BEZONS", codePostal: "95", zone: "A" },
  { nom: "BIEVRES", codePostal: "91", zone: "A" },
  { nom: "BOBIGNY", codePostal: "93", zone: "A" },
  { nom: "BOIS COLOMBES", codePostal: "92", zone: "A" },
  { nom: "BOISSY ST LEGER", codePostal: "94", zone: "A" },
  { nom: "BONDY", codePostal: "93", zone: "A" },
  { nom: "BONNEUIL EN FRANCE", codePostal: "95", zone: "A" },
  { nom: "BONNEUIL SUR MARNE", codePostal: "94", zone: "A" },
  { nom: "BOUFFEMONT", codePostal: "95", zone: "A" },
  { nom: "BOULOGNE BILLANCOURT", codePostal: "92", zone: "A" },
  { nom: "BOURDONNE", codePostal: "78", zone: "A" },
  { nom: "BOURG LA REINE", codePostal: "92", zone: "A" },
  { nom: "BREANCON", codePostal: "95", zone: "A" },
  { nom: "BRETIGNY SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "BROU SUR CHANTEREINE", codePostal: "77", zone: "A" },
  { nom: "BRY SUR MARNE", codePostal: "94", zone: "A" },
  { nom: "BUSSY ST GEORGES", codePostal: "77", zone: "A" },
  { nom: "BUTRY SUR OISE", codePostal: "95", zone: "A" },
  { nom: "CACHAN", codePostal: "94", zone: "A" },
  { nom: "CARNETIN", codePostal: "77", zone: "A" },
  { nom: "CARRIERES SUR SEINE", codePostal: "78", zone: "A" },
  { nom: "CERGY ST CHRISTOPHE", codePostal: "95", zone: "A" },
  { nom: "CHAMPIGNY SUR MARNE", codePostal: "94", zone: "A" },
  { nom: "CHAMPLAN", codePostal: "91", zone: "A" },
  { nom: "CHAMPS SUR MARNE", codePostal: "77", zone: "A" },
  { nom: "CHANTELOUP EN BRIE", codePostal: "77", zone: "A" },
  { nom: "CHARENTON", codePostal: "94", zone: "A" },
  { nom: "CHARMENTRAY", codePostal: "77", zone: "A" },
  { nom: "CHARMONT", codePostal: "95", zone: "A" },
  { nom: "CHARNY", codePostal: "77", zone: "A" },
  { nom: "CHATENAY EN FRANCE", codePostal: "95", zone: "A" },
  { nom: "CHATENAY MALABRY", codePostal: "92", zone: "A" },
  { nom: "CHATILLON", codePostal: "92", zone: "A" },
  { nom: "CHATOU", codePostal: "78", zone: "A" },
  { nom: "CHAUMONTEL", codePostal: "95", zone: "A" },
  { nom: "CHAUVRY", codePostal: "95", zone: "A" },
  { nom: "CHAVILLE", codePostal: "92", zone: "A" },
  { nom: "CHELLES", codePostal: "77", zone: "A" },
  { nom: "CHENNEVIERES LES LOUVRES", codePostal: "95", zone: "A" },
  { nom: "CHENNEVIERES SUR MARNE", codePostal: "94", zone: "A" },
  { nom: "CHEVILLY LA RUE", codePostal: "94", zone: "A" },
  { nom: "CHILLY MAZARIN", codePostal: "91", zone: "A" },
  { nom: "CHOISY LE ROI", codePostal: "94", zone: "A" },
  { nom: "CLAMART", codePostal: "92", zone: "A" },
  { nom: "CLAYE SOUILLY", codePostal: "77", zone: "A" },
  { nom: "CLERY EN VEXIN", codePostal: "95", zone: "A" },
  { nom: "CLICHY SOUS BOIS", codePostal: "93", zone: "A" },
  { nom: "CLICHY SUR SEINE", codePostal: "92", zone: "A" },
  { nom: "COLLEGIEN", codePostal: "77", zone: "A" },
  { nom: "COLOMBES", codePostal: "92", zone: "A" },
  { nom: "COMPANS", codePostal: "77", zone: "A" },
  { nom: "CONCHES", codePostal: "77", zone: "A" },
  { nom: "CONDE SUR VESGRE", codePostal: "78", zone: "A" },
  { nom: "CONFLANS STE HONORINE", codePostal: "78", zone: "A" },
  { nom: "CORMEILLES EN PARISIS", codePostal: "95", zone: "A" },
  { nom: "COUBRON", codePostal: "93", zone: "A" },
  { nom: "COURBEVOIE", codePostal: "92", zone: "A" },
  { nom: "COURDIMANCHE", codePostal: "95", zone: "A" },
  { nom: "COURTRY", codePostal: "77", zone: "A" },
  { nom: "CRETEIL", codePostal: "94", zone: "A" },
  { nom: "CROISSY BEAUBOURG", codePostal: "77", zone: "A" },
  { nom: "CROISSY SUR SEINE", codePostal: "78", zone: "A" },
  { nom: "CROSNE", codePostal: "91", zone: "A" },
  { nom: "DAMMARTIN EN GOELE", codePostal: "77", zone: "A" },
  { nom: "DAMMARTIN EN SERVE", codePostal: "78", zone: "A" },
  { nom: "DAMPMART", codePostal: "77", zone: "A" },
  { nom: "DEUIL LA BARRE", codePostal: "95", zone: "A" },
  { nom: "DOMONT", codePostal: "95", zone: "A" },
  { nom: "DRANCY", codePostal: "93", zone: "A" },
  { nom: "DRAVEIL", codePostal: "91", zone: "A" },
  { nom: "DUGNY", codePostal: "93", zone: "A" },
  { nom: "EAUBONNE", codePostal: "95", zone: "A" },
  { nom: "ECOUEN", codePostal: "95", zone: "A" },
  { nom: "EMERAINVILLE", codePostal: "77", zone: "A" },
  { nom: "ENGHIEN LES BAINS", codePostal: "95", zone: "A" },
  { nom: "ENNERY", codePostal: "95", zone: "A" },
  { nom: "EPIAIS LES LOUVRES", codePostal: "95", zone: "A" },
  { nom: "EPINAY CHAMPLATREUX", codePostal: "95", zone: "A" },
  { nom: "EPINAY SOUS SENART", codePostal: "91", zone: "A" },
  { nom: "EPINAY SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "EPINAY SUR SEINE", codePostal: "93", zone: "A" },
  { nom: "ERAGNY", codePostal: "95", zone: "A" },
  { nom: "ERMONT", codePostal: "95", zone: "A" },
  { nom: "EZANVILLE", codePostal: "95", zone: "A" },
  { nom: "FLEURY MEROGIS", codePostal: "91", zone: "A" },
  { nom: "FONTENAY AUX ROSES", codePostal: "92", zone: "A" },
  { nom: "FONTENAY EN PARISIS", codePostal: "95", zone: "A" },
  { nom: "FONTENAY SOUS BOIS", codePostal: "94", zone: "A" },
  { nom: "FOSSES", codePostal: "95", zone: "A" },
  { nom: "FOURQUEUX", codePostal: "78", zone: "A" },
  { nom: "FRANCONVILLE", codePostal: "95", zone: "A" },
  { nom: "FRESNES", codePostal: "94", zone: "A" },
  { nom: "FRESNES SUR MARNE", codePostal: "77", zone: "A" },
  { nom: "FROUVILLE", codePostal: "95", zone: "A" },
  { nom: "GAGNY", codePostal: "93", zone: "A" },
  { nom: "GARCHES", codePostal: "92", zone: "A" },
  { nom: "GARGES LES GONESSES", codePostal: "95", zone: "A" },
  { nom: "GENAINVILLE", codePostal: "95", zone: "A" },
  { nom: "GENNEVILLIERS", codePostal: "92", zone: "A" },
  { nom: "GENTILLY", codePostal: "94", zone: "A" },
  { nom: "GONESSE", codePostal: "95", zone: "A" },
  { nom: "GOURNAY SUR MARNE", codePostal: "93", zone: "A" },
  { nom: "GOUSSAINVILLE", codePostal: "95", zone: "A" },
  { nom: "GOUVERNES", codePostal: "77", zone: "A" },
  { nom: "GRANDCHAMP", codePostal: "78", zone: "A" },
  { nom: "GRESSY", codePostal: "77", zone: "A" },
  { nom: "GRIGNY", codePostal: "91", zone: "A" },
  { nom: "GROSLAY", codePostal: "95", zone: "A" },
  { nom: "GUERMANTES", codePostal: "77", zone: "A" },
  { nom: "HEDOUVILLE", codePostal: "95", zone: "A" },
  { nom: "HERBLAY", codePostal: "95", zone: "A" },
  { nom: "HOUILLES", codePostal: "78", zone: "A" },
  { nom: "IGNY", codePostal: "91", zone: "A" },
  { nom: "ILE SAINT DENIS", codePostal: "93", zone: "A" },
  { nom: "ISSY LES MOULINEAUX", codePostal: "92", zone: "A" },
  { nom: "IVRY SUR SEINE", codePostal: "94", zone: "A" },
  { nom: "JABLINES", codePostal: "77", zone: "A" },
  { nom: "JOINVILLE LE PONT", codePostal: "94", zone: "A" },
  { nom: "JOSSIGNY", codePostal: "77", zone: "A" },
  { nom: "JUILLY", codePostal: "77", zone: "A" },
  { nom: "JUVISY SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "KREMLIN BICETRE", codePostal: "94", zone: "A" },
  { nom: "L'HAY LES ROSES", codePostal: "94", zone: "A" },
  { nom: "LA CELLE ST CLOUD", codePostal: "78", zone: "A" },
  { nom: "LA CHAPELLE EN VEXIN", codePostal: "95", zone: "A" },
  { nom: "LA COURNEUVE", codePostal: "93", zone: "A" },
  { nom: "LA DEFENSE", codePostal: "92", zone: "A" },
  { nom: "LA FRETTE SUR SEINE", codePostal: "95", zone: "A" },
  { nom: "LA GARENNE COLOMBES", codePostal: "92", zone: "A" },
  { nom: "LA HAUTEVILLE", codePostal: "78", zone: "A" },
  { nom: "LA QUEUE EN BRIE", codePostal: "94", zone: "A" },
  { nom: "LA VARENNE ST HILAIRE", codePostal: "94", zone: "A" },
  { nom: "LAGNY SUR MARNE", codePostal: "77", zone: "A" },
  { nom: "LASSY", codePostal: "95", zone: "A" },
  { nom: "LE BLANC MESNIL", codePostal: "93", zone: "A" },
  { nom: "LE BOURGET", codePostal: "93", zone: "A" },
  { nom: "LE CHESNAY", codePostal: "78", zone: "A" },
  { nom: "LE PERREUX", codePostal: "94", zone: "A" },
  { nom: "LE PIN", codePostal: "77", zone: "A" },
  { nom: "LE PLESSIS BOUCHARD", codePostal: "95", zone: "A" },
  { nom: "LE PLESSIS LUZARCHES", codePostal: "95", zone: "A" },
  { nom: "LE PLESSIS PATE", codePostal: "91", zone: "A" },
  { nom: "LE PLESSIS ROBINSON", codePostal: "92", zone: "A" },
  { nom: "LE PLESSIS TREVISE", codePostal: "94", zone: "A" },
  { nom: "LE PRE ST GERVAIS", codePostal: "93", zone: "A" },
  { nom: "LE RAINCY", codePostal: "93", zone: "A" },
  { nom: "LE THILLAY", codePostal: "95", zone: "A" },
  { nom: "LE VESINET", codePostal: "78", zone: "A" },
  { nom: "LES LILAS", codePostal: "93", zone: "A" },
  { nom: "LEVALLOIS PERRET", codePostal: "92", zone: "A" },
  { nom: "LIMEIL BREVANNES", codePostal: "94", zone: "A" },
  { nom: "LIVRY GARGAN", codePostal: "93", zone: "A" },
  { nom: "LOGNES", codePostal: "77", zone: "A" },
  { nom: "LONGJUMEAU", codePostal: "91", zone: "A" },
  { nom: "LONGPERRIER", codePostal: "77", zone: "A" },
  { nom: "LONGPONT SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "LOUVRES", codePostal: "78", zone: "A" },
  { nom: "LUZARCHES", codePostal: "95", zone: "A" },
  { nom: "MAFFLIERS", codePostal: "95", zone: "A" },
  { nom: "MAISONS ALFORT", codePostal: "94", zone: "A" },
  { nom: "MAISONS LAFFITTE", codePostal: "78", zone: "A" },
  { nom: "MALAKOFF", codePostal: "92", zone: "A" },
  { nom: "MANDRES LES ROSES", codePostal: "94", zone: "A" },
  { nom: "MARCHEMORET", codePostal: "77", zone: "A" },
  { nom: "MARGENCY", codePostal: "95", zone: "A" },
  { nom: "MARINES", codePostal: "95", zone: "A" },
  { nom: "MARLY LA VILLE", codePostal: "95", zone: "A" },
  { nom: "MARNE LA COQUETTE", codePostal: "92", zone: "A" },
  { nom: "MAROLLES EN BRIE", codePostal: "77", zone: "A" },
  { nom: "MASSY", codePostal: "91", zone: "A" },
  { nom: "MAUREGARD", codePostal: "77", zone: "A" },
  { nom: "MENNECY", codePostal: "91", zone: "A" },
  { nom: "MENUCOURT", codePostal: "95", zone: "A" },
  { nom: "MERIEL", codePostal: "95", zone: "A" },
  { nom: "MERY SUR OISE", codePostal: "95", zone: "A" },
  { nom: "MESSY", codePostal: "77", zone: "A" },
  { nom: "MEUDON LA FORET", codePostal: "92", zone: "A" },
  { nom: "MITRY MORY", codePostal: "77", zone: "A" },
  { nom: "MOISSELLES", codePostal: "95", zone: "A" },
  { nom: "MONTESSON", codePostal: "78", zone: "A" },
  { nom: "MONTFERMEIL", codePostal: "93", zone: "A" },
  { nom: "MONTGE EN GOELE", codePostal: "77", zone: "A" },
  { nom: "MONTGERON", codePostal: "91", zone: "A" },
  { nom: "MONTIGNY LES CORMEILLES", codePostal: "95", zone: "A" },
  { nom: "MONTLIGNON", codePostal: "95", zone: "A" },
  { nom: "MONTMAGNY", codePostal: "78", zone: "A" },
  { nom: "MONTMORENCY", codePostal: "95", zone: "A" },
  { nom: "MONTREUIL", codePostal: "93", zone: "A" },
  { nom: "MONTROUGE", codePostal: "92", zone: "A" },
  { nom: "MONTSOULT", codePostal: "95", zone: "A" },
  { nom: "MORANGIS", codePostal: "91", zone: "A" },
  { nom: "MORSANG SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "MORSANG SUR SEINE", codePostal: "91", zone: "A" },
  { nom: "MOURS", codePostal: "95", zone: "A" },
  { nom: "MOUSSY", codePostal: "95", zone: "A" },
  { nom: "MOUSSY LE NEUF", codePostal: "77", zone: "A" },
  { nom: "MOUSSY LE VIEUX", codePostal: "77", zone: "A" },
  { nom: "NANTERRE", codePostal: "92", zone: "A" },
  { nom: "NANTOUILLET", codePostal: "77", zone: "A" },
  { nom: "NEUILLY EN VEXIN", codePostal: "95", zone: "A" },
  { nom: "NEUILLY PLAISANCE", codePostal: "93", zone: "A" },
  { nom: "NEUILLY SUR MARNE", codePostal: "93", zone: "A" },
  { nom: "NEUILLY SUR SEINE", codePostal: "92", zone: "A" },
  { nom: "NOGENT SUR MARNE", codePostal: "94", zone: "A" },
  { nom: "NOISEAU", codePostal: "94", zone: "A" },
  { nom: "NOISIEL", codePostal: "77", zone: "A" },
  { nom: "NOISY LE GRAND", codePostal: "93", zone: "A" },
  { nom: "NOISY LE SEC", codePostal: "93", zone: "A" },
  { nom: "NOISY SUR OISE", codePostal: "95", zone: "A" },
  { nom: "ORLY", codePostal: "94", zone: "A" },
  { nom: "ORLY FRET", codePostal: "94", zone: "A" },
  { nom: "OSNY", codePostal: "95", zone: "A" },
  { nom: "OTHIS", codePostal: "77", zone: "A" },
  { nom: "PALAISEAU", codePostal: "91", zone: "A" },
  { nom: "PANTIN", codePostal: "93", zone: "A" },
  { nom: "PARAY VIEILLE POSTE", codePostal: "91", zone: "A" },
  { nom: "PARIS", codePostal: "75", zone: "A" },
  { nom: "PARMAIN", codePostal: "95", zone: "A" },
  { nom: "PAVILLONS SOUS BOIS", codePostal: "93", zone: "A" },
  { nom: "PERIGNY SUR YERRES", codePostal: "94", zone: "A" },
  { nom: "PERSAN", codePostal: "95", zone: "A" },
  { nom: "PIERREFITTE", codePostal: "93", zone: "A" },
  { nom: "PIERRELAYE", codePostal: "95", zone: "A" },
  { nom: "PISCOP", codePostal: "95", zone: "A" },
  { nom: "POMPONNE", codePostal: "77", zone: "A" },
  { nom: "PONTAULT COMBAULT", codePostal: "77", zone: "A" },
  { nom: "PONTOISE", codePostal: "95", zone: "A" },
  { nom: "PORT MARLY", codePostal: "78", zone: "A" },
  { nom: "PRECY SUR MARNE", codePostal: "77", zone: "A" },
  { nom: "PUISEUX EN FRANCE", codePostal: "95", zone: "A" },
  { nom: "PUISEUX PONTOISE", codePostal: "95", zone: "A" },
  { nom: "PUTEAUX", codePostal: "92", zone: "A" },
  { nom: "QUINCY SOUS SENART", codePostal: "91", zone: "A" },
  { nom: "RIS ORANGIS", codePostal: "91", zone: "A" },
  { nom: "ROISSY EN BRIE", codePostal: "77", zone: "A" },
  { nom: "ROISSY EN FRANCE", codePostal: "95", zone: "A" },
  { nom: "ROMAINVILLE", codePostal: "93", zone: "A" },
  { nom: "ROSNY S/BOIS", codePostal: "93", zone: "A" },
  { nom: "ROUVRES", codePostal: "77", zone: "A" },
  { nom: "RUEIL MALMAISON", codePostal: "92", zone: "A" },
  { nom: "RUNGIS", codePostal: "94", zone: "A" },
  { nom: "SAINT CLOUD", codePostal: "92", zone: "A" },
  { nom: "SAINTRY SUR SEINE", codePostal: "91", zone: "A" },
  { nom: "SANNOIS", codePostal: "95", zone: "A" },
  { nom: "SANTENY", codePostal: "94", zone: "A" },
  { nom: "SARCELLES", codePostal: "95", zone: "A" },
  { nom: "SARTROUVILLE", codePostal: "78", zone: "A" },
  { nom: "SAULX LES CHARTREUX", codePostal: "91", zone: "A" },
  { nom: "SAVIGNY SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "SCEAUX", codePostal: "92", zone: "A" },
  { nom: "SEUGY", codePostal: "95", zone: "A" },
  { nom: "SEVRAN", codePostal: "93", zone: "A" },
  { nom: "SEVRES", codePostal: "92", zone: "A" },
  { nom: "SOISY SOUS MONTMORENCY", codePostal: "95", zone: "A" },
  { nom: "ST BRICE SOUS FORET", codePostal: "95", zone: "A" },
  { nom: "ST DENIS", codePostal: "93", zone: "A" },
  { nom: "ST GERMAIN EN LAYE", codePostal: "78", zone: "A" },
  { nom: "ST GERMAIN LES CORBEILS", codePostal: "91", zone: "A" },
  { nom: "ST GRATIEN", codePostal: "95", zone: "A" },
  { nom: "ST LEU LA FORET", codePostal: "95", zone: "A" },
  { nom: "ST MANDE", codePostal: "94", zone: "A" },
  { nom: "ST MARD", codePostal: "77", zone: "A" },
  { nom: "ST MAUR DES FOSSES", codePostal: "94", zone: "A" },
  { nom: "ST MAURICE", codePostal: "94", zone: "A" },
  { nom: "ST MESMES", codePostal: "77", zone: "A" },
  { nom: "ST OUEN", codePostal: "93", zone: "A" },
  { nom: "ST OUEN L'AUMONE", codePostal: "95", zone: "A" },
  { nom: "ST PIERRE DU PERRAY", codePostal: "91", zone: "A" },
  { nom: "ST PRIX", codePostal: "95", zone: "A" },
  { nom: "ST THIBAULT DES VIGNES", codePostal: "77", zone: "A" },
  { nom: "ST WITZ", codePostal: "95", zone: "A" },
  { nom: "STAINS", codePostal: "93", zone: "A" },
  { nom: "SUCY EN BRIE", codePostal: "94", zone: "A" },
  { nom: "SURESNES", codePostal: "92", zone: "A" },
  { nom: "SURVILLIERS", codePostal: "95", zone: "A" },
  { nom: "TAVERNY", codePostal: "95", zone: "A" },
  { nom: "THIAIS", codePostal: "94", zone: "A" },
  { nom: "THIEUX", codePostal: "77", zone: "A" },
  { nom: "THORIGNY SUR MARNE", codePostal: "77", zone: "A" },
  { nom: "TORCY", codePostal: "77", zone: "A" },
  { nom: "VAIRES SUR MARNE", codePostal: "77", zone: "A" },
  { nom: "VALENTON", codePostal: "94", zone: "A" },
  { nom: "VALLANGOUJARD", codePostal: "95", zone: "A" },
  { nom: "VANVES", codePostal: "92", zone: "A" },
  { nom: "VAUCRESSON", codePostal: "92", zone: "A" },
  { nom: "VAUDHERLAND", codePostal: "95", zone: "A" },
  { nom: "VAUHALLAN", codePostal: "91", zone: "A" },
  { nom: "VAUJOURS", codePostal: "93", zone: "A" },
  { nom: "VELIZY VILLACOUBLAY", codePostal: "78", zone: "A" },
  { nom: "VEMARS", codePostal: "95", zone: "A" },
  { nom: "VERRIERES LE BUISSON", codePostal: "91", zone: "A" },
  { nom: "VERSAILLES", codePostal: "78", zone: "C" },
  { nom: "VIARMES", codePostal: "95", zone: "A" },
  { nom: "VIGNEUX SUR SEINE", codePostal: "91", zone: "A" },
  { nom: "VILLAINES SOUS BOIS", codePostal: "95", zone: "A" },
  { nom: "VILLE D'AVRAY", codePostal: "92", zone: "A" },
  { nom: "VILLECRESNES", codePostal: "94", zone: "A" },
  { nom: "VILLEJUIF", codePostal: "94", zone: "A" },
  { nom: "VILLEJUST", codePostal: "91", zone: "A" },
  { nom: "VILLEMOISSON SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "VILLEMONBLE", codePostal: "93", zone: "A" },
  { nom: "VILLENEUVE LA GARENNE", codePostal: "92", zone: "A" },
  { nom: "VILLENEUVE LE ROI", codePostal: "94", zone: "A" },
  { nom: "VILLENEUVE SOUS DAMMARTIN", codePostal: "77", zone: "A" },
  { nom: "VILLENEUVE ST GEORGES", codePostal: "94", zone: "A" },
  { nom: "VILLEPARISIS", codePostal: "77", zone: "A" },
  { nom: "VILLERON", codePostal: "95", zone: "A" },
  { nom: "VILLEROY", codePostal: "77", zone: "A" },
  { nom: "VILLETANEUSE", codePostal: "93", zone: "A" },
  { nom: "VILLEVAUDE", codePostal: "77", zone: "A" },
  { nom: "VILLIERS LE BEL", codePostal: "95", zone: "A" },
  { nom: "VILLIERS SUR MARNES", codePostal: "94", zone: "A" },
  { nom: "VILLIERS SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "VINANTES", codePostal: "77", zone: "A" },
  { nom: "VINCENNES", codePostal: "94", zone: "A" },
  { nom: "VIROFLAY", codePostal: "78", zone: "A" },
  { nom: "VIRY CHATILLON", codePostal: "91", zone: "A" },
  { nom: "VITRY SUR SEINE", codePostal: "94", zone: "A" },
  { nom: "WISSOUS", codePostal: "91", zone: "A" },
  { nom: "YERRES", codePostal: "91", zone: "A" },

  // Zone B
  { nom: "AIGREMONT", codePostal: "78", zone: "B" },
  { nom: "AMBLEVILLE", codePostal: "95", zone: "B" },
  { nom: "AMENUCOURT", codePostal: "95", zone: "B" },
  { nom: "ARPAJON", codePostal: "91", zone: "B" },
  { nom: "AUVERNAUX", codePostal: "91", zone: "B" },
  { nom: "AUVERS ST GEORGES", codePostal: "91", zone: "B" },
  { nom: "AUVERS SUR OISE", codePostal: "95", zone: "B" },
  { nom: "AVRAINVILLE", codePostal: "91", zone: "B" },
  { nom: "BABY", codePostal: "77", zone: "B" },
  { nom: "BAILLY", codePostal: "78", zone: "B" },
  { nom: "BAILLY ROMAINVILLIERS", codePostal: "77", zone: "B" },
  { nom: "BALLAINVILLIERS", codePostal: "91", zone: "B" },
  { nom: "BARCY", codePostal: "77", zone: "B" },
  { nom: "BERNES SUR OISE", codePostal: "95", zone: "B" },
  { nom: "BERVILLE", codePostal: "95", zone: "B" },
  { nom: "BETHEMONT LA FORET", codePostal: "95", zone: "B" },
  { nom: "BOINVILLIERS", codePostal: "78", zone: "B" },
  { nom: "BOIS D'ARCY", codePostal: "78", zone: "B" },
  { nom: "BOISSY L'AILLERIE", codePostal: "95", zone: "B" },
  { nom: "BOISSY MAUVOISIN", codePostal: "78", zone: "B" },
  { nom: "BONDOUFLE", codePostal: "91", zone: "B" },
  { nom: "BOUAFLE", codePostal: "78", zone: "B" },
  { nom: "BOUGIVAL", codePostal: "78", zone: "B" },
  { nom: "BOULLAY LES TROUX", codePostal: "91", zone: "B" },
  { nom: "BOUQUEVAL", codePostal: "95", zone: "B" },
  { nom: "BOUSSY ST ANTOINE", codePostal: "91", zone: "B" },
  { nom: "BRAY ET LU", codePostal: "95", zone: "B" },
  { nom: "BREUILLET", codePostal: "91", zone: "B" },
  { nom: "BRIE COMTE ROBERT", codePostal: "77", zone: "B" },
  { nom: "BRUEIL EN VEXIN", codePostal: "78", zone: "B" },
  { nom: "BRUNOY", codePostal: "91", zone: "B" },
  { nom: "BRUYERES LE CHATEL", codePostal: "91", zone: "B" },
  { nom: "BRUYERES SUR OISE", codePostal: "95", zone: "B" },
  { nom: "BUC", codePostal: "78", zone: "B" },
  { nom: "BUHY", codePostal: "95", zone: "B" },
  { nom: "BURES SUR YVETTE", codePostal: "91", zone: "B" },
  { nom: "BUSSY ST MARTIN", codePostal: "77", zone: "B" },
  { nom: "CARRIERES SOUS POISSY", codePostal: "78", zone: "B" },
  { nom: "CHAMBOURCY", codePostal: "78", zone: "B" },
  { nom: "CHAMBRY", codePostal: "77", zone: "B" },
  { nom: "CHAMPAGNE SUR OISE", codePostal: "95", zone: "B" },
  { nom: "CHANTELOUP LES VIGNES", codePostal: "78", zone: "B" },
  { nom: "CHARS", codePostal: "95", zone: "B" },
  { nom: "CHATEAUFORT", codePostal: "78", zone: "B" },
  { nom: "CHAUCONIN NEUFMONTIERS", codePostal: "77", zone: "B" },
  { nom: "CHAUFFOUR LES ETRECHY", codePostal: "91", zone: "B" },
  { nom: "CHAUSSY", codePostal: "95", zone: "B" },
  { nom: "CHAVENAY", codePostal: "78", zone: "B" },
  { nom: "CHEPTAINVILLE", codePostal: "91", zone: "B" },
  { nom: "CHESSY", codePostal: "77", zone: "B" },
  { nom: "CHEVRY COSSIGNY", codePostal: "77", zone: "B" },
  { nom: "CLAIREFONTAINE EN YVELINES", codePostal: "78", zone: "B" },
  { nom: "COIGNIERES", codePostal: "78", zone: "B" },
  { nom: "COMBS LA VILLE", codePostal: "77", zone: "B" },
  { nom: "CORBEIL ESSONNES", codePostal: "91", zone: "B" },
  { nom: "CORMEILLES EN VEXIN", codePostal: "95", zone: "B" },
  { nom: "COUBERT", codePostal: "77", zone: "B" },
  { nom: "COUPVRAY", codePostal: "77", zone: "B" },
  { nom: "COURANCES", codePostal: "91", zone: "B" },
  { nom: "COURCELLES SUR VIOSNE", codePostal: "95", zone: "B" },
  { nom: "COURCOURONNES", codePostal: "91", zone: "B" },
  { nom: "COURTABOEUF", codePostal: "91", zone: "B" },
  { nom: "CREGY LES MEAUX", codePostal: "77", zone: "B" },
  { nom: "CUISY", codePostal: "77", zone: "B" },
  { nom: "DOUE", codePostal: "77", zone: "B" },
  { nom: "DROCOURT", codePostal: "78", zone: "B" },
  { nom: "ECQUEVILLY", codePostal: "78", zone: "B" },
  { nom: "ELANCOURT", codePostal: "78", zone: "B" },
  { nom: "EMANCE", codePostal: "78", zone: "B" },
  { nom: "EPIAIS RHUS", codePostal: "95", zone: "B" },
  { nom: "ESBLY", codePostal: "77", zone: "B" },
  { nom: "ETIOLLES", codePostal: "91", zone: "B" },
  { nom: "ETRECHY", codePostal: "91", zone: "B" },
  { nom: "EVRY", codePostal: "91", zone: "B" },
  { nom: "FAVRIEUX", codePostal: "78", zone: "B" },
  { nom: "FERRIERES EN BRIE", codePostal: "77", zone: "B" },
  { nom: "FONTENAY LE FLEURY", codePostal: "78", zone: "B" },
  { nom: "FONTENAY LE VICOMTE", codePostal: "91", zone: "B" },
  { nom: "FONTENAY ST PERE", codePostal: "78", zone: "B" },
  { nom: "FONTENAY TRESIGNY", codePostal: "77", zone: "B" },
  { nom: "FORFRY", codePostal: "77", zone: "B" },
  { nom: "FORGES LES BAINS", codePostal: "91", zone: "B" },
  { nom: "FREMECOURT", codePostal: "95", zone: "B" },
  { nom: "FREPILLON", codePostal: "95", zone: "B" },
  { nom: "FUBLAINES", codePostal: "77", zone: "B" },
  { nom: "GENICOURT", codePostal: "95", zone: "B" },
  { nom: "GERMIGNY L'EVEQUE", codePostal: "77", zone: "B" },
  { nom: "GESVRES LE CHAPITRE", codePostal: "77", zone: "B" },
  { nom: "GIF SUR YVETTE", codePostal: "91", zone: "B" },
  { nom: "GOMETZ LA VILLE", codePostal: "91", zone: "B" },
  { nom: "GOMETZ LE CHATEL", codePostal: "91", zone: "B" },
  { nom: "GRETZ ARMAINVILLIERS", codePostal: "77", zone: "B" },
  { nom: "GRISY LES PLATRES", codePostal: "95", zone: "B" },
  { nom: "GUITRANCOURT", codePostal: "78", zone: "B" },
  { nom: "GUYANCOURT", codePostal: "78", zone: "B" },
  { nom: "HARAVILLIERS", codePostal: "95", zone: "B" },
  { nom: "HAUTE ISLE", codePostal: "95", zone: "B" },
  { nom: "HERMERAY", codePostal: "78", zone: "B" },
  { nom: "HEROUVILLE", codePostal: "95", zone: "B" },
  { nom: "HONDEVILLIERS", codePostal: "77", zone: "B" },
  { nom: "ISLES LES VILLENOY", codePostal: "77", zone: "B" },
  { nom: "IVERNY", codePostal: "77", zone: "B" },
  { nom: "JAGNY SOUS BOIS", codePostal: "95", zone: "B" },
  { nom: "JOUY EN JOSAS", codePostal: "78", zone: "B" },
  { nom: "JOUY LE CHATEL", codePostal: "77", zone: "B" },
  { nom: "L'ISLE ADAM", codePostal: "95", zone: "B" },
  { nom: "LA BOISSIERE ECOLE", codePostal: "78", zone: "B" },
  { nom: "LA HOUSSAYE EN BRIE", codePostal: "77", zone: "B" },
  { nom: "LA ROCHE GUYON", codePostal: "95", zone: "B" },
  { nom: "LA VERRIERE", codePostal: "78", zone: "B" },
  { nom: "LA VILLE DU BOIS", codePostal: "91", zone: "B" },
  { nom: "LABBEVILLE", codePostal: "95", zone: "B" },
  { nom: "LE BELLAY EN VEXIN", codePostal: "95", zone: "B" },
  { nom: "LE COUDRAY MONTCEAUX", codePostal: "91", zone: "B" },
  { nom: "LE HEAULME", codePostal: "95", zone: "B" },
  { nom: "LE MESNIL AUBRY", codePostal: "95", zone: "B" },
  { nom: "LE MESNIL LE ROI", codePostal: "77", zone: "B" },
  { nom: "LE PECQ", codePostal: "78", zone: "B" },
  { nom: "LE PLESSIS GASSOT", codePostal: "95", zone: "B" },
  { nom: "LE TARTRE GAUDRAN", codePostal: "78", zone: "B" },
  { nom: "LES ULIS", codePostal: "91", zone: "B" },
  { nom: "LESCHES", codePostal: "77", zone: "B" },
  { nom: "LESIGNY", codePostal: "77", zone: "B" },
  { nom: "LEUVILLE SUR ORGE", codePostal: "91", zone: "B" },
  { nom: "LIEUSAINT", codePostal: "77", zone: "B" },
  { nom: "LISSES", codePostal: "91", zone: "B" },
  { nom: "LIVILLIERS", codePostal: "95", zone: "B" },
  { nom: "LIVRY SUR SEINE", codePostal: "77", zone: "B" },
  { nom: "LOUVECIENNES", codePostal: "78", zone: "B" },
  { nom: "MAGNY LE HONGRE", codePostal: "77", zone: "B" },
  { nom: "MAGNY LES HAMEAUX", codePostal: "78", zone: "B" },
  { nom: "MARCOUSSIS", codePostal: "91", zone: "B" },
  { nom: "MAREIL EN FRANCE", codePostal: "95", zone: "B" },
  { nom: "MAREUIL LES MEAUX", codePostal: "77", zone: "B" },
  { nom: "MARLY LE ROI", codePostal: "78", zone: "B" },
  { nom: "MAURECOURT", codePostal: "78", zone: "B" },
  { nom: "MAUREPAS", codePostal: "78", zone: "B" },
  { nom: "MEAUX", codePostal: "77", zone: "B" },
  { nom: "MENOUVILLE", codePostal: "95", zone: "B" },
  { nom: "MITTAINVILLE", codePostal: "78", zone: "B" },
  { nom: "MONTCEAUX LES MEAUX", codePostal: "77", zone: "B" },
  { nom: "MONTEVRAIN", codePostal: "77", zone: "B" },
  { nom: "MONTGEROULT", codePostal: "95", zone: "B" },
  { nom: "MONTHYON", codePostal: "77", zone: "B" },
  { nom: "MONTIGNY LE BRETONNEUX", codePostal: "78", zone: "B" },
  { nom: "MONTREUIL SUR EPTE", codePostal: "95", zone: "B" },
  { nom: "MONTRY", codePostal: "77", zone: "B" },
  { nom: "NANTEUIL LES MEAUX", codePostal: "77", zone: "B" },
  { nom: "NERVILLE LA FORET", codePostal: "95", zone: "B" },
  { nom: "NESLES LA VALLEE", codePostal: "95", zone: "B" },
  { nom: "NOINTEL", codePostal: "95", zone: "B" },
  { nom: "NORVILLE", codePostal: "77", zone: "B" },
  { nom: "NOZAY", codePostal: "91", zone: "B" },
  { nom: "OISSERY", codePostal: "77", zone: "B" },
  { nom: "OLLAINVILLE", codePostal: "91", zone: "B" },
  { nom: "ORCEMONT", codePostal: "78", zone: "B" },
  { nom: "ORGEVAL", codePostal: "78", zone: "B" },
  { nom: "ORMOY", codePostal: "91", zone: "B" },
  { nom: "ORSAY", codePostal: "91", zone: "B" },
  { nom: "OZOIR LA FERRIERE", codePostal: "77", zone: "B" },
  { nom: "PENCHARD", codePostal: "77", zone: "B" },
  { nom: "PLAISIR", codePostal: "78", zone: "B" },
  { nom: "PLESSIS AUX BOIS", codePostal: "77", zone: "B" },
  { nom: "PLESSIS L'EVEQUE", codePostal: "77", zone: "B" },
  { nom: "POINCY", codePostal: "77", zone: "B" },
  { nom: "POISSY", codePostal: "78", zone: "B" },
  { nom: "PONTCARRE", codePostal: "77", zone: "B" },
  { nom: "PRESLES", codePostal: "95", zone: "B" },
  { nom: "PRESLES EN BRIE", codePostal: "77", zone: "B" },
  { nom: "QUINCY VOISINS", codePostal: "77", zone: "B" },
  { nom: "RONQUEROLLES", codePostal: "95", zone: "B" },
  { nom: "SACLAY", codePostal: "91", zone: "B" },
  { nom: "SANTEUIL", codePostal: "95", zone: "B" },
  { nom: "SERRIS", codePostal: "77", zone: "B" },
  { nom: "SERVON", codePostal: "77", zone: "B" },
  { nom: "SOISY SUR SEINE", codePostal: "91", zone: "B" },
  { nom: "SOUZY LA BRICHE", codePostal: "91", zone: "B" },
  { nom: "ST AUBIN", codePostal: "91", zone: "B" },
  { nom: "ST CLAIR SUR EPTE", codePostal: "95", zone: "B" },
  { nom: "ST CYR L'ECOLE", codePostal: "78", zone: "B" },
  { nom: "ST FIACRE", codePostal: "77", zone: "B" },
  { nom: "ST GERMAIN LES ARPAJONS", codePostal: "91", zone: "B" },
  { nom: "ST MARTIN DU TERTRE", codePostal: "95", zone: "B" },
  { nom: "ST MICHEL SUR ORGE", codePostal: "91", zone: "B" },
  { nom: "ST NOM LA BRETECHE", codePostal: "78", zone: "B" },
  { nom: "ST PATHUS", codePostal: "77", zone: "B" },
  { nom: "ST SOUPPLETS", codePostal: "77", zone: "B" },
  { nom: "STE GENEVIEVE DES BOIS", codePostal: "91", zone: "B" },
  { nom: "TIGERY", codePostal: "91", zone: "B" },
  { nom: "TOURNAN EN BRIE", codePostal: "77", zone: "B" },
  { nom: "TOUSSUS LE NOBLE", codePostal: "78", zone: "B" },
  { nom: "TRAPPES", codePostal: "78", zone: "B" },
  { nom: "TRIEL SUR SEINE", codePostal: "78", zone: "B" },
  { nom: "TRILBARDOU", codePostal: "77", zone: "B" },
  { nom: "TRILPORT", codePostal: "77", zone: "B" },
  { nom: "US", codePostal: "95", zone: "B" },
  { nom: "VALMONDOIS", codePostal: "95", zone: "B" },
  { nom: "VARENNES JARCY", codePostal: "91", zone: "B" },
  { nom: "VARREDDES", codePostal: "77", zone: "B" },
  { nom: "VERNEUIL SUR SEINE", codePostal: "78", zone: "B" },
  { nom: "VETHEUIL", codePostal: "95", zone: "B" },
  { nom: "VIGNELY", codePostal: "77", zone: "B" },
  { nom: "VIGNY", codePostal: "95", zone: "B" },
  { nom: "VILLABE", codePostal: "91", zone: "B" },
  { nom: "VILLEBON SUR YVETTE", codePostal: "91", zone: "B" },
  { nom: "VILLECONIN", codePostal: "91", zone: "B" },
  { nom: "VILLEMAREUIL", codePostal: "77", zone: "B" },
  { nom: "VILLENEUVE SUR AUVERS", codePostal: "91", zone: "B" },
  { nom: "VILLENNES SUR SEINE", codePostal: "78", zone: "B" },
  { nom: "VILLENOY", codePostal: "77", zone: "B" },
  { nom: "VILLEPREUX", codePostal: "78", zone: "B" },
  { nom: "VILLERS EN ARTHIES", codePostal: "95", zone: "B" },
  { nom: "VILLIERS ADAM", codePostal: "95", zone: "B" },
  { nom: "VILLIERS LE BACLE", codePostal: "91", zone: "B" },
  { nom: "VILLIERS LE SEC", codePostal: "95", zone: "B" },
  { nom: "VILLIERS ST FREDERIC", codePostal: "78", zone: "B" },
  { nom: "VOISINS LE BRETONNEUX", codePostal: "78", zone: "B" },
  { nom: "YEBLES", codePostal: "77", zone: "B" },

  // Zone C
  { nom: "ABBEVILLE LA RIVIERE", codePostal: "91", zone: "C" },
  { nom: "ABLEIGES", codePostal: "95", zone: "C" },
  { nom: "ABLIS", codePostal: "78", zone: "C" },
  { nom: "ACHERES LA FORET", codePostal: "77", zone: "C" },
  { nom: "ALLAINVILLE", codePostal: "78", zone: "C" },
  { nom: "ALLUETS LE ROI", codePostal: "78", zone: "C" },
  { nom: "AMILLIS", codePostal: "77", zone: "C" },
  { nom: "AMPONVILLE", codePostal: "77", zone: "C" },
  { nom: "ANDELU", codePostal: "78", zone: "C" },
  { nom: "ANDREZEL", codePostal: "77", zone: "C" },
  { nom: "ANGERVILLE", codePostal: "91", zone: "C" },
  { nom: "ANGERVILLIERS", codePostal: "91", zone: "C" },
  { nom: "ARBONNE LA FORET", codePostal: "77", zone: "C" },
  { nom: "ARGENTIERES", codePostal: "77", zone: "C" },
  { nom: "ARMENTIERES EN BRIE", codePostal: "77", zone: "C" },
  { nom: "ARNOUVILLE LES MANTES", codePostal: "78", zone: "C" },
  { nom: "ARRANCOURT", codePostal: "91", zone: "C" },
  { nom: "ARRONVILLE", codePostal: "95", zone: "C" },
  { nom: "ARVILLE", codePostal: "77", zone: "C" },
  { nom: "AUBEPIERRE", codePostal: "77", zone: "C" },
  { nom: "AUBERGENVILLE", codePostal: "78", zone: "C" },
  { nom: "AUFFARGIS", codePostal: "78", zone: "C" },
  { nom: "AUFFERVILLE", codePostal: "77", zone: "C" },
  { nom: "AUFFREVILLE BRASSEUIL", codePostal: "78", zone: "C" },
  { nom: "AUGERS EN BRIE", codePostal: "77", zone: "C" },
  { nom: "AULNAY SUR MAULDRE", codePostal: "78", zone: "C" },
  { nom: "AULNOY", codePostal: "77", zone: "C" },
  { nom: "AUTEUIL", codePostal: "78", zone: "C" },
  { nom: "AUTHON LA PLAINE", codePostal: "91", zone: "C" },
  { nom: "AUTOUILLET", codePostal: "78", zone: "C" },
  { nom: "AVERNES", codePostal: "95", zone: "C" },
  { nom: "AVON", codePostal: "77", zone: "C" },
  { nom: "BAGNEAUX SUR LOING", codePostal: "77", zone: "C" },
  { nom: "BALLOY", codePostal: "77", zone: "C" },
  { nom: "BANNOST VILLEGAGNON", codePostal: "77", zone: "C" },
  { nom: "BARBEY", codePostal: "77", zone: "C" },
  { nom: "BARBIZON", codePostal: "77", zone: "C" },
  { nom: "BASSEVELLE", codePostal: "77", zone: "C" },
  { nom: "BAULNE", codePostal: "91", zone: "C" },
  { nom: "BAZAINVILLE", codePostal: "78", zone: "C" },
  { nom: "BAZEMONT", codePostal: "78", zone: "C" },
  { nom: "BAZOCHES LES BRAY", codePostal: "77", zone: "C" },
  { nom: "BAZOCHES SUR GUYONNE", codePostal: "78", zone: "C" },
  { nom: "BEAUCHERY SAINT MARTIN", codePostal: "77", zone: "C" },
  { nom: "BEAUMONT DU GATINAIS", codePostal: "77", zone: "C" },
  { nom: "BEAUTHEIL", codePostal: "77", zone: "C" },
  { nom: "BEAUVOIR", codePostal: "77", zone: "C" },
  { nom: "BEHOUST", codePostal: "78", zone: "C" },
  { nom: "BELLOT", codePostal: "77", zone: "C" },
  { nom: "BENNECOURT", codePostal: "78", zone: "C" },
  { nom: "BERNAY VILBERT", codePostal: "77", zone: "C" },
  { nom: "BETON BAZOCHES", codePostal: "77", zone: "C" },
  { nom: "BEYNES", codePostal: "78", zone: "C" },
  { nom: "BEZALLES", codePostal: "77", zone: "C" },
  { nom: "BLANDY", codePostal: "77", zone: "C" },
  { nom: "BLARU", codePostal: "78", zone: "C" },
  { nom: "BLENNES", codePostal: "77", zone: "C" },
  { nom: "BOIGNEVILLE", codePostal: "91", zone: "C" },
  { nom: "BOINVILLE EN MANTOIS", codePostal: "78", zone: "C" },
  { nom: "BOINVILLE LE GAILLARD", codePostal: "78", zone: "C" },
  { nom: "BOIS HERPIN", codePostal: "91", zone: "C" },
  { nom: "BOIS LE ROI", codePostal: "77", zone: "C" },
  { nom: "BOISDON", codePostal: "77", zone: "C" },
  { nom: "BOISSETS", codePostal: "78", zone: "C" },
  { nom: "BOISSETTES", codePostal: "77", zone: "C" },
  { nom: "BOISSISE LA BERTRAND", codePostal: "77", zone: "C" },
  { nom: "BOISSISE LE ROI", codePostal: "77", zone: "C" },
  { nom: "BOISSY AUX CAILLES", codePostal: "77", zone: "C" },
  { nom: "BOISSY LA RIVIERE", codePostal: "91", zone: "C" },
  { nom: "BOISSY LE CHATEL", codePostal: "77", zone: "C" },
  { nom: "BOISSY LE CUTTE", codePostal: "91", zone: "C" },
  { nom: "BOISSY LE SEC", codePostal: "91", zone: "C" },
  { nom: "BOISSY SANS AVOIR", codePostal: "78", zone: "C" },
  { nom: "BOISSY SOUS ST YON", codePostal: "91", zone: "C" },
  { nom: "BOITRON", codePostal: "77", zone: "C" },
  { nom: "BOMBON", codePostal: "77", zone: "C" },
  { nom: "BONNELLES", codePostal: "78", zone: "C" },
  { nom: "BONNIERES SUR SEINE", codePostal: "78", zone: "C" },
  { nom: "BOUGLIGNY", codePostal: "77", zone: "C" },
  { nom: "BOULANCOURT", codePostal: "77", zone: "C" },
  { nom: "BOULEURS", codePostal: "77", zone: "C" },
  { nom: "BOURAY SUR JUINE", codePostal: "91", zone: "C" },
  { nom: "BOURRON MARLOTTE", codePostal: "77", zone: "C" },
  { nom: "BOUTERVILLIERS", codePostal: "91", zone: "C" },
  { nom: "BOUTIGNY", codePostal: "77", zone: "C" },
  { nom: "BOUTIGNY SUR ESSONNE", codePostal: "91", zone: "C" },
  { nom: "BOUVILLE", codePostal: "91", zone: "C" },
  { nom: "BRANSLES", codePostal: "77", zone: "C" },
  { nom: "BRAY SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "BREAU", codePostal: "77", zone: "C" },
  { nom: "BREUIL BOIS ROBERT", codePostal: "78", zone: "C" },
  { nom: "BREUX JOUY", codePostal: "91", zone: "C" },
  { nom: "BREVAL", codePostal: "78", zone: "C" },
  { nom: "BRIERES LES SCELLES", codePostal: "91", zone: "C" },
  { nom: "BRIGNANCOURT", codePostal: "95", zone: "C" },
  { nom: "BRIIS SOUS FORGES", codePostal: "91", zone: "C" },
  { nom: "BROSSE MONTCEAUX", codePostal: "77", zone: "C" },
  { nom: "BROUY", codePostal: "91", zone: "C" },
  { nom: "BUCHELAY", codePostal: "78", zone: "C" },
  { nom: "BULLION", codePostal: "78", zone: "C" },
  { nom: "BUNO BONNEVAUX", codePostal: "91", zone: "C" },
  { nom: "BURCY", codePostal: "77", zone: "C" },
  { nom: "BUSSIERES", codePostal: "77", zone: "C" },
  { nom: "BUTHIERS", codePostal: "77", zone: "C" },
  { nom: "CANNES ECLUSE", codePostal: "77", zone: "C" },
  { nom: "CELLE SUR MORIN", codePostal: "77", zone: "C" },
  { nom: "CELY", codePostal: "77", zone: "C" },
  { nom: "CERNAY LA VILLE", codePostal: "78", zone: "C" },
  { nom: "CERNEUX", codePostal: "77", zone: "C" },
  { nom: "CERNY", codePostal: "91", zone: "C" },
  { nom: "CESSON", codePostal: "77", zone: "C" },
  { nom: "CESSOY EN MONTOIS", codePostal: "77", zone: "C" },
  { nom: "CHAILLY EN BIERE", codePostal: "77", zone: "C" },
  { nom: "CHAILLY EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CHAINTREAUX", codePostal: "77", zone: "C" },
  { nom: "CHALAUTRE LA GRANDE", codePostal: "77", zone: "C" },
  { nom: "CHALAUTRE LA PETITE", codePostal: "77", zone: "C" },
  { nom: "CHALIFERT", codePostal: "77", zone: "C" },
  { nom: "CHALMAISON", codePostal: "77", zone: "C" },
  { nom: "CHALO ST MARS", codePostal: "91", zone: "C" },
  { nom: "CHALOU MOULINEUX", codePostal: "91", zone: "C" },
  { nom: "CHAMARANDE", codePostal: "91", zone: "C" },
  { nom: "CHAMIGNY", codePostal: "77", zone: "C" },
  { nom: "CHAMPAGNE SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "CHAMPCENEST", codePostal: "77", zone: "C" },
  { nom: "CHAMPCUEIL", codePostal: "91", zone: "C" },
  { nom: "CHAMPDEUIL", codePostal: "77", zone: "C" },
  { nom: "CHAMPEAUX", codePostal: "77", zone: "C" },
  { nom: "CHAMPMOTTEUX", codePostal: "91", zone: "C" },
  { nom: "CHANGIS SUR MARNE", codePostal: "77", zone: "C" },
  { nom: "CHAPELLE GAUTHIER", codePostal: "77", zone: "C" },
  { nom: "CHAPELLE IGER", codePostal: "77", zone: "C" },
  { nom: "CHAPELLE LA REINE", codePostal: "77", zone: "C" },
  { nom: "CHAPELLE RABLAIS", codePostal: "77", zone: "C" },
  { nom: "CHAPELLE SAINT SULPICE", codePostal: "77", zone: "C" },
  { nom: "CHAPET", codePostal: "78", zone: "C" },
  { nom: "CHARTRETTES", codePostal: "77", zone: "C" },
  { nom: "CHARTRONGES", codePostal: "77", zone: "C" },
  { nom: "CHATEAU LANDON", codePostal: "77", zone: "C" },
  { nom: "CHATEAUBLEAU", codePostal: "77", zone: "C" },
  { nom: "CHATELET EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CHATENAY SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "CHATENOY", codePostal: "77", zone: "C" },
  { nom: "CHATIGNONVILLE", codePostal: "91", zone: "C" },
  { nom: "CHATILLON LA BORDE", codePostal: "77", zone: "C" },
  { nom: "CHATRES", codePostal: "77", zone: "C" },
  { nom: "CHAUFFRY", codePostal: "77", zone: "C" },
  { nom: "CHAUFOUR LES BONNIERES", codePostal: "78", zone: "C" },
  { nom: "CHAUMES EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CHENOISE", codePostal: "77", zone: "C" },
  { nom: "CHENOU", codePostal: "77", zone: "C" },
  { nom: "CHERENCE", codePostal: "95", zone: "C" },
  { nom: "CHEVANNES", codePostal: "91", zone: "C" },
  { nom: "CHEVRAINVILLIERS", codePostal: "77", zone: "C" },
  { nom: "CHEVREUSE", codePostal: "78", zone: "C" },
  { nom: "CHEVRU", codePostal: "77", zone: "C" },
  { nom: "CHEVRY EN SEREINE", codePostal: "77", zone: "C" },
  { nom: "CHOISEL", codePostal: "78", zone: "C" },
  { nom: "CHOISY EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CITRY", codePostal: "77", zone: "C" },
  { nom: "CIVRY LA FORET", codePostal: "78", zone: "C" },
  { nom: "CLOS FONTAINE", codePostal: "77", zone: "C" },
  { nom: "COCHEREL", codePostal: "77", zone: "C" },
  { nom: "COMMENY", codePostal: "95", zone: "C" },
  { nom: "CONDE STE LIBIAIRE", codePostal: "77", zone: "C" },
  { nom: "CONDECOURT", codePostal: "95", zone: "C" },
  { nom: "CONGERVILLE", codePostal: "91", zone: "C" },
  { nom: "CONGIS SUR THEROUANNE", codePostal: "77", zone: "C" },
  { nom: "CORBREUSE", codePostal: "91", zone: "C" },
  { nom: "COUILLY PONT AUX DAMES", codePostal: "77", zone: "C" },
  { nom: "COULOMBS EN VALOIS", codePostal: "77", zone: "C" },
  { nom: "COULOMMES", codePostal: "77", zone: "C" },
  { nom: "COULOMMIERS", codePostal: "77", zone: "C" },
  { nom: "COURCELLES EN BASSEE", codePostal: "77", zone: "C" },
  { nom: "COURCHAMP", codePostal: "77", zone: "C" },
  { nom: "COURDIMANCHE SUR ESSONNE", codePostal: "91", zone: "C" },
  { nom: "COURGENT", codePostal: "78", zone: "C" },
  { nom: "COURPALAY", codePostal: "77", zone: "C" },
  { nom: "COURQUETAINE", codePostal: "77", zone: "C" },
  { nom: "COURSON MONTELOUP", codePostal: "91", zone: "C" },
  { nom: "COURTACON", codePostal: "77", zone: "C" },
  { nom: "COURTOMER", codePostal: "77", zone: "C" },
  { nom: "COUTENCON", codePostal: "77", zone: "C" },
  { nom: "COUTEVROULT", codePostal: "77", zone: "C" },
  { nom: "CRAVENT", codePostal: "78", zone: "C" },
  { nom: "CRECY LA CHAPELLE", codePostal: "77", zone: "C" },
  { nom: "CRESPIERES", codePostal: "78", zone: "C" },
  { nom: "CREVECOEUR EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CRISENOY", codePostal: "77", zone: "C" },
  { nom: "CROIX EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CROUY SUR OURCQ", codePostal: "77", zone: "C" },
  { nom: "CUCHARMOY", codePostal: "77", zone: "C" },
  { nom: "D'HUISON LONGUEVILLE", codePostal: "91", zone: "C" },
  { nom: "DAGNY", codePostal: "77", zone: "C" },
  { nom: "DAMMARIE LES LYS", codePostal: "77", zone: "C" },
  { nom: "DAMMARTIN SUR TIGEAUX", codePostal: "77", zone: "C" },
  { nom: "DAMPIERRE EN YVELINES", codePostal: "78", zone: "C" },
  { nom: "DANNEMARIE", codePostal: "78", zone: "C" },
  { nom: "DANNEMOIS", codePostal: "91", zone: "C" },
  { nom: "DARVAULT", codePostal: "77", zone: "C" },
  { nom: "DAVRON", codePostal: "78", zone: "C" },
  { nom: "DHUISY", codePostal: "77", zone: "C" },
  { nom: "DIANT", codePostal: "77", zone: "C" },
  { nom: "DONNEMARIE DONTILLY", codePostal: "77", zone: "C" },
  { nom: "DORMELLES", codePostal: "77", zone: "C" },
  { nom: "DOURDAN", codePostal: "91", zone: "C" },
  { nom: "DOUY LA RAMEE", codePostal: "77", zone: "C" },
  { nom: "ECHARCON", codePostal: "91", zone: "C" },
  { nom: "ECHOUBOULAINS", codePostal: "77", zone: "C" },
  { nom: "ECRENNES", codePostal: "77", zone: "C" },
  { nom: "ECUELLES", codePostal: "77", zone: "C" },
  { nom: "EGLIGNY", codePostal: "77", zone: "C" },
  { nom: "EGLY", codePostal: "91", zone: "C" },
  { nom: "EGREVILLE", codePostal: "77", zone: "C" },
  { nom: "EPISY", codePostal: "77", zone: "C" },
  { nom: "EPONE", codePostal: "78", zone: "C" },
  { nom: "ESMANS", codePostal: "77", zone: "C" },
  { nom: "ESTOUCHES", codePostal: "91", zone: "C" },
  { nom: "ETAMPES", codePostal: "91", zone: "C" },
  { nom: "ETREPILLY", codePostal: "77", zone: "C" },
  { nom: "EVECQUEMONT", codePostal: "78", zone: "C" },
  { nom: "EVERLY", codePostal: "77", zone: "C" },
  { nom: "EVRY GREGY SUR YERRE", codePostal: "77", zone: "C" },
  { nom: "FAREMOUTIERS", codePostal: "77", zone: "C" },
  { nom: "FAVIERES", codePostal: "77", zone: "C" },
  { nom: "FAY LES NEMOURS", codePostal: "77", zone: "C" },
  { nom: "FERICY", codePostal: "77", zone: "C" },
  { nom: "FEROLLES ATTILLY", codePostal: "77", zone: "C" },
  { nom: "FERTE GAUCHER", codePostal: "77", zone: "C" },
  { nom: "FERTE SOUS JOUARRE", codePostal: "77", zone: "C" },
  { nom: "FEUCHEROLLES", codePostal: "78", zone: "C" },
  { nom: "FLACOURT", codePostal: "78", zone: "C" },
  { nom: "FLAGY", codePostal: "77", zone: "C" },
  { nom: "FLEURY EN BIERE", codePostal: "77", zone: "C" },
  { nom: "FLEXANVILLE", codePostal: "78", zone: "C" },
  { nom: "FLINS NEUVE EGLISE", codePostal: "78", zone: "C" },
  { nom: "FLINS SUR SEINE", codePostal: "78", zone: "C" },
  { nom: "FOLLAINVILLE DENNEMONT", codePostal: "78", zone: "C" },
  { nom: "FONTAINE FOURCHES", codePostal: "77", zone: "C" },
  { nom: "FONTAINE LA RIVIERE", codePostal: "91", zone: "C" },
  { nom: "FONTAINE LE PORT", codePostal: "77", zone: "C" },
  { nom: "FONTAINEBLEAU", codePostal: "77", zone: "C" },
  { nom: "FONTAINS", codePostal: "77", zone: "C" },
  { nom: "FONTENAILLES", codePostal: "77", zone: "C" },
  { nom: "FONTENAY LES BRIIS", codePostal: "91", zone: "C" },
  { nom: "FONTENAY MAUVOISIN", codePostal: "78", zone: "C" },
  { nom: "FORGES", codePostal: "77", zone: "C" },
  { nom: "FOUJU", codePostal: "77", zone: "C" },
  { nom: "FREMAINVILLE", codePostal: "95", zone: "C" },
  { nom: "FRENEUSE", codePostal: "78", zone: "C" },
  { nom: "FRETOY", codePostal: "77", zone: "C" },
  { nom: "FROMONT", codePostal: "77", zone: "C" },
  { nom: "GADANCOURT", codePostal: "95", zone: "C" },
  { nom: "GAILLON SUR MONTCIENT", codePostal: "78", zone: "C" },
  { nom: "GALLUIS", codePostal: "78", zone: "C" },
  { nom: "GAMBAIS", codePostal: "78", zone: "C" },
  { nom: "GAMBAISEUIL", codePostal: "78", zone: "C" },
  { nom: "GARANCIERES", codePostal: "78", zone: "C" },
  { nom: "GARENTREVILLE", codePostal: "77", zone: "C" },
  { nom: "GARGENVILLE", codePostal: "78", zone: "C" },
  { nom: "GASTINS", codePostal: "77", zone: "C" },
  { nom: "GAZERAN", codePostal: "78", zone: "C" },
  { nom: "GENEVRAYE", codePostal: "77", zone: "C" },
  { nom: "GERMIGNY SOUS COLOMBS", codePostal: "77", zone: "C" },
  { nom: "GIREMOUTIERS", codePostal: "77", zone: "C" },
  { nom: "GIRONVILLE", codePostal: "77", zone: "C" },
  { nom: "GIRONVILLE SUR ESSONNE", codePostal: "91", zone: "C" },
  { nom: "GOMMECOURT", codePostal: "78", zone: "C" },
  { nom: "GOUAIX", codePostal: "77", zone: "C" },
  { nom: "GOUPILLIERES", codePostal: "78", zone: "C" },
  { nom: "GOUSSONVILLE", codePostal: "78", zone: "C" },
  { nom: "GOUZANGREZ", codePostal: "95", zone: "C" },
  { nom: "GRANDPUITS BAILLY CARROIS", codePostal: "77", zone: "C" },
  { nom: "GRAVON", codePostal: "77", zone: "C" },
  { nom: "GRESSEY", codePostal: "78", zone: "C" },
  { nom: "GREZ SUR LOING", codePostal: "77", zone: "C" },
  { nom: "GRISY SUISNES", codePostal: "77", zone: "C" },
  { nom: "GRISY SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "GROSROUVRE", codePostal: "78", zone: "C" },
  { nom: "GUERARD", codePostal: "77", zone: "C" },
  { nom: "GUERCHEVILLE", codePostal: "77", zone: "C" },
  { nom: "GUERNES", codePostal: "78", zone: "C" },
  { nom: "GUERVILLE", codePostal: "78", zone: "C" },
  { nom: "GUIBEVILLE", codePostal: "91", zone: "C" },
  { nom: "GUIGNES", codePostal: "77", zone: "C" },
  { nom: "GUIGNEVILLE SUR ESSONNE", codePostal: "91", zone: "C" },
  { nom: "GUILLERVAL", codePostal: "91", zone: "C" },
  { nom: "GUIRY EN VEXIN", codePostal: "95", zone: "C" },
  { nom: "GURCY LE CHATEL", codePostal: "77", zone: "C" },
  { nom: "HARDRICOURT", codePostal: "78", zone: "C" },
  { nom: "HARGEVILLE", codePostal: "78", zone: "C" },
  { nom: "HAUTE MAISON", codePostal: "77", zone: "C" },
  { nom: "HAUTEFEUILLE", codePostal: "77", zone: "C" },
  { nom: "HERBEVILLE", codePostal: "78", zone: "C" },
  { nom: "HERICY", codePostal: "77", zone: "C" },
  { nom: "HERME", codePostal: "77", zone: "C" },
  { nom: "HODENT", codePostal: "95", zone: "C" },
  { nom: "HOUDAN", codePostal: "78", zone: "C" },
  { nom: "ICHY", codePostal: "77", zone: "C" },
  { nom: "ISLES LES MELDEUSES", codePostal: "77", zone: "C" },
  { nom: "ISSOU", codePostal: "78", zone: "C" },
  { nom: "ITTEVILLE", codePostal: "91", zone: "C" },
  { nom: "JAIGNES", codePostal: "77", zone: "C" },
  { nom: "JAMBVILLE", codePostal: "78", zone: "C" },
  { nom: "JANVILLE SUR JUINE", codePostal: "91", zone: "C" },
  { nom: "JANVRY", codePostal: "91", zone: "C" },
  { nom: "JAULNES", codePostal: "77", zone: "C" },
  { nom: "JEUFOSSE", codePostal: "78", zone: "C" },
  { nom: "JOUARRE", codePostal: "77", zone: "C" },
  { nom: "JOUARS PONTCHARTRAIN", codePostal: "78", zone: "C" },
  { nom: "JOUY MAUVOISIN", codePostal: "78", zone: "C" },
  { nom: "JOUY SUR MORIN", codePostal: "77", zone: "C" },
  { nom: "JUMEAUVILLE", codePostal: "78", zone: "C" },
  { nom: "JUTIGNY", codePostal: "77", zone: "C" },
  { nom: "JUZIERS", codePostal: "78", zone: "C" },
  { nom: "L'ETANG LA VILLE", codePostal: "78", zone: "C" },
  { nom: "LA CELLE LES BORDES", codePostal: "78", zone: "C" },
  { nom: "LA CHAPELLE MOUTILS", codePostal: "77", zone: "C" },
  { nom: "LA FALAISE", codePostal: "78", zone: "C" },
  { nom: "LA FERTE ALAIS", codePostal: "91", zone: "C" },
  { nom: "LA FORET LE ROI", codePostal: "91", zone: "C" },
  { nom: "LA FORET STE CROIX", codePostal: "91", zone: "C" },
  { nom: "LA GRANDE PAROISSE", codePostal: "77", zone: "C" },
  { nom: "LA QUEUE LES YVELINES", codePostal: "78", zone: "C" },
  { nom: "LA ROCHETTE", codePostal: "77", zone: "C" },
  { nom: "LA VILLENEUVE EN CHEVRIE", codePostal: "78", zone: "C" },
  { nom: "LAINVILLE", codePostal: "78", zone: "C" },
  { nom: "LARCHANT", codePostal: "77", zone: "C" },
  { nom: "LARDY", codePostal: "91", zone: "C" },
  { nom: "LAVAL EN BRIE", codePostal: "77", zone: "C" },
  { nom: "LE MESNIL ST DENIS", codePostal: "78", zone: "C" },
  { nom: "LE PERCHAY", codePostal: "95", zone: "C" },
  { nom: "LE PERRAY EN YVELINES", codePostal: "78", zone: "C" },
  { nom: "LE TERTRE ST DENIS", codePostal: "78", zone: "C" },
  { nom: "LE TREMBLAY SUR MAULDRE", codePostal: "78", zone: "C" },
  { nom: "LE VAL ST GERMAIN", codePostal: "91", zone: "C" },
  { nom: "LECHELLE", codePostal: "77", zone: "C" },
  { nom: "LES BREVIAIRES", codePostal: "78", zone: "C" },
  { nom: "LES CHAPELLES BOURBONS", codePostal: "77", zone: "C" },
  { nom: "LES CLAYES SOUS BOIS", codePostal: "78", zone: "C" },
  { nom: "LES ESSARTS LE ROI", codePostal: "78", zone: "C" },
  { nom: "LES GRANGES LE ROI", codePostal: "91", zone: "C" },
  { nom: "LES LOGES EN JOSAS", codePostal: "78", zone: "C" },
  { nom: "LES MESNULS", codePostal: "78", zone: "C" },
  { nom: "LES MOLIERES", codePostal: "91", zone: "C" },
  { nom: "LES MUREAUX", codePostal: "78", zone: "C" },
  { nom: "LES ORMES SUR VOULZIE", codePostal: "77", zone: "C" },
  { nom: "LESCHEROLLES", codePostal: "77", zone: "C" },
  { nom: "LEUDEVILLE", codePostal: "91", zone: "C" },
  { nom: "LEUDON EN BRIE", codePostal: "77", zone: "C" },
  { nom: "LEVIS ST NOM", codePostal: "78", zone: "C" },
  { nom: "LIMAY", codePostal: "78", zone: "C" },
  { nom: "LIMETZ VILLEZ", codePostal: "78", zone: "C" },
  { nom: "LIMOGES FOURCHES", codePostal: "77", zone: "C" },
  { nom: "LIMOURS", codePostal: "91", zone: "C" },
  { nom: "LINAS", codePostal: "91", zone: "C" },
  { nom: "LISSY", codePostal: "77", zone: "C" },
  { nom: "LIVERDY EN BRIE", codePostal: "77", zone: "C" },
  { nom: "LIZINES", codePostal: "77", zone: "C" },
  { nom: "LIZY SUR OURCQ", codePostal: "77", zone: "C" },
  { nom: "LOMMOYE", codePostal: "78", zone: "C" },
  { nom: "LONGNES", codePostal: "78", zone: "C" },
  { nom: "LONGUESSE", codePostal: "95", zone: "C" },
  { nom: "LONGUEVILLE", codePostal: "77", zone: "C" },
  { nom: "LONGVILLIERS", codePostal: "78", zone: "C" },
  { nom: "LORREZ LE BOCAGE PREAUX", codePostal: "77", zone: "C" },
  { nom: "LOUAN VILLEGRUIS FONTAINE", codePostal: "77", zone: "C" },
  { nom: "LUISETAINES", codePostal: "77", zone: "C" },
  { nom: "LUMIGNY NESLES ORMEAUX", codePostal: "77", zone: "C" },
  { nom: "LUZANCY", codePostal: "77", zone: "C" },
  { nom: "MACHAULT", codePostal: "77", zone: "C" },
  { nom: "MADELEINE SUR LOING", codePostal: "77", zone: "C" },
  { nom: "MAGNANVILLE", codePostal: "78", zone: "C" },
  { nom: "MAGNY EN VEXIN", codePostal: "95", zone: "C" },
  { nom: "MAINCY", codePostal: "77", zone: "C" },
  { nom: "MAISON ROUGE", codePostal: "77", zone: "C" },
  { nom: "MAISONCELL", codePostal: "78", zone: "C" },
  { nom: "MAISONCELLES EN BRIE", codePostal: "77", zone: "C" },
  { nom: "MAISONCELLES EN GATINAIS", codePostal: "77", zone: "C" },
  { nom: "MAISSE", codePostal: "91", zone: "C" },
  { nom: "MANTES LA JOLIE", codePostal: "78", zone: "C" },
  { nom: "MANTES LA VILLE", codePostal: "78", zone: "C" },
  { nom: "MARCILLY", codePostal: "77", zone: "C" },
  { nom: "MARCQ", codePostal: "78", zone: "C" },
  { nom: "MAREIL LE GUYON", codePostal: "78", zone: "C" },
  { nom: "MAREIL MARLY", codePostal: "78", zone: "C" },
  { nom: "MAREIL SUR MAULDRE", codePostal: "78", zone: "C" },
  { nom: "MARETS", codePostal: "77", zone: "C" },
  { nom: "MARLES EN BRIE", codePostal: "77", zone: "C" },
  { nom: "MAROLLES EN BEAUCE", codePostal: "91", zone: "C" },
  { nom: "MAROLLES EN BRIE", codePostal: "77", zone: "C" },
  { nom: "MAROLLES EN HUREPOIX", codePostal: "91", zone: "C" },
  { nom: "MAROLLES SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "MARY SUR MARNE", codePostal: "77", zone: "C" },
  { nom: "MAUCHAMPS", codePostal: "91", zone: "C" },
  { nom: "MAUDETOUR EN VEXIN", codePostal: "95", zone: "C" },
  { nom: "MAULE", codePostal: "78", zone: "C" },
  { nom: "MAULETTE", codePostal: "78", zone: "C" },
  { nom: "MAUPERTHUIS", codePostal: "77", zone: "C" },
  { nom: "MAY EN MULTIEN", codePostal: "77", zone: "C" },
  { nom: "MEDAN", codePostal: "78", zone: "C" },
  { nom: "MEE SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "MEIGNEUX", codePostal: "77", zone: "C" },
  { nom: "MEILLERAY", codePostal: "77", zone: "C" },
  { nom: "MELUN", codePostal: "77", zone: "C" },
  { nom: "MELZ SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "MENERVILLE", codePostal: "78", zone: "C" },
  { nom: "MERE", codePostal: "78", zone: "C" },
  { nom: "MEREVILLE", codePostal: "91", zone: "C" },
  { nom: "MERICOURT", codePostal: "95", zone: "C" },
  { nom: "MEROBERT", codePostal: "91", zone: "C" },
  { nom: "MERY SUR MARNE", codePostal: "77", zone: "C" },
  { nom: "MESPUITS", codePostal: "91", zone: "C" },
  { nom: "MEULAN", codePostal: "78", zone: "C" },
  { nom: "MEZIERES SUR SEINE", codePostal: "78", zone: "C" },
  { nom: "MEZY SUR SEINE", codePostal: "78", zone: "C" },
  { nom: "MILLEMONT", codePostal: "78", zone: "C" },
  { nom: "MILLY LA FORET", codePostal: "91", zone: "C" },
  { nom: "MILON LA CHAPELLE", codePostal: "78", zone: "C" },
  { nom: "MISY SUR YONNE", codePostal: "77", zone: "C" },
  { nom: "MOIGNY SUR ECOLE", codePostal: "91", zone: "C" },
  { nom: "MOISENAY", codePostal: "77", zone: "C" },
  { nom: "MOISSON", codePostal: "78", zone: "C" },
  { nom: "MOISSY CRAMAYEL", codePostal: "77", zone: "C" },
  { nom: "MONDEVILLE", codePostal: "91", zone: "C" },
  { nom: "MONDREVILLE", codePostal: "77", zone: "C" },
  { nom: "MONNERVILLE", codePostal: "91", zone: "C" },
  { nom: "MONS EN MONTOIS", codePostal: "77", zone: "C" },
  { nom: "MONTAINVILLE", codePostal: "78", zone: "C" },
  { nom: "MONTALET LE BOIS", codePostal: "78", zone: "C" },
  { nom: "MONTARLOT", codePostal: "77", zone: "C" },
  { nom: "MONTCEAUX LES PROVINS", codePostal: "77", zone: "C" },
  { nom: "MONTCHAUVET", codePostal: "78", zone: "C" },
  { nom: "MONTCOURT FROMONVILLE", codePostal: "77", zone: "C" },
  { nom: "MONTDAUPHIN", codePostal: "77", zone: "C" },
  { nom: "MONTENILS", codePostal: "77", zone: "C" },
  { nom: "MONTEREAU FAULT YONNE", codePostal: "77", zone: "C" },
  { nom: "MONTEREAU SUR LE JARD", codePostal: "77", zone: "C" },
  { nom: "MONTFORT L'AMAURY", codePostal: "78", zone: "C" },
  { nom: "MONTIGNY LE GUESDIER", codePostal: "77", zone: "C" },
  { nom: "MONTIGNY LENCOUP", codePostal: "77", zone: "C" },
  { nom: "MONTIGNY SUR LOING", codePostal: "77", zone: "C" },
  { nom: "MONTLHERY", codePostal: "91", zone: "C" },
  { nom: "MONTMACHOUX", codePostal: "77", zone: "C" },
  { nom: "MONTOLIVET", codePostal: "77", zone: "C" },
  { nom: "MORAINVILLIERS", codePostal: "78", zone: "C" },
  { nom: "MORET SUR LOING", codePostal: "77", zone: "C" },
  { nom: "MORIGNY CHAMPIGNY", codePostal: "91", zone: "C" },
  { nom: "MORMANT", codePostal: "77", zone: "C" },
  { nom: "MORTCERF", codePostal: "77", zone: "C" },
  { nom: "MORTERY", codePostal: "77", zone: "C" },
  { nom: "MOUROUX", codePostal: "77", zone: "C" },
  { nom: "MOUSSEAUX LES BRAY", codePostal: "77", zone: "C" },
  { nom: "MOUSSEAUX SUR SEINE", codePostal: "78", zone: "C" },
  { nom: "MOUY SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "MULCENT", codePostal: "78", zone: "C" },
  { nom: "NAINVILLE LES ROCHES", codePostal: "91", zone: "C" },
  { nom: "NANDY", codePostal: "77", zone: "C" },
  { nom: "NANGIS", codePostal: "77", zone: "C" },
  { nom: "NANTEAU SUR ESSONNE", codePostal: "77", zone: "C" },
  { nom: "NANTEAU SUR LUNAIN", codePostal: "77", zone: "C" },
  { nom: "NANTEUIL SUR MARNE", codePostal: "77", zone: "C" },
  { nom: "NEAUPHLE LE CHATEAU", codePostal: "78", zone: "C" },
  { nom: "NEAUPHLE LE VIEUX", codePostal: "78", zone: "C" },
  { nom: "NEAUPHLETTE", codePostal: "95", zone: "C" },
  { nom: "NEMOURS", codePostal: "77", zone: "C" },
  { nom: "NEUFMOUTIERS EN BRIE", codePostal: "77", zone: "C" },
  { nom: "NEZEL", codePostal: "78", zone: "C" },
  { nom: "NOISY LE ROI", codePostal: "78", zone: "C" },
  { nom: "NOISY RUDIGNON", codePostal: "77", zone: "C" },
  { nom: "NOISY SUR ECOLE", codePostal: "77", zone: "C" },
  { nom: "NONVILLE", codePostal: "78", zone: "C" },
  { nom: "NOYEN SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "NUCOURT", codePostal: "95", zone: "C" },
  { nom: "OBSONVILLE", codePostal: "77", zone: "C" },
  { nom: "OCQUERRE", codePostal: "77", zone: "C" },
  { nom: "OINVILLE SUR MONTCIENT", codePostal: "78", zone: "C" },
  { nom: "OMERVILLE", codePostal: "95", zone: "C" },
  { nom: "ONCY SUR ECOLE", codePostal: "91", zone: "C" },
  { nom: "ORGENOY", codePostal: "78", zone: "C" },
  { nom: "ORGERUS", codePostal: "78", zone: "C" },
  { nom: "ORLY SUR MORIN", codePostal: "77", zone: "C" },
  { nom: "ORMESSON", codePostal: "77", zone: "C" },
  { nom: "ORMOY LA RIVIERE", codePostal: "91", zone: "C" },
  { nom: "ORPHIN", codePostal: "77", zone: "C" },
  { nom: "ORSONVILLE", codePostal: "78", zone: "C" },
  { nom: "ORVEAU", codePostal: "91", zone: "C" },
  { nom: "ORVILLIERS", codePostal: "78", zone: "C" },
  { nom: "OSMOY", codePostal: "78", zone: "C" },
  { nom: "OZOUER LE VOULGIS", codePostal: "77", zone: "C" },
  { nom: "PALEY", codePostal: "77", zone: "C" },
  { nom: "PAMFOU", codePostal: "77", zone: "C" },
  { nom: "PARAY DOUAVILLE", codePostal: "78", zone: "C" },
  { nom: "PAROY", codePostal: "77", zone: "C" },
  { nom: "PASSY SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "PECQUEUSE", codePostal: "91", zone: "C" },
  { nom: "PECY", codePostal: "77", zone: "C" },
  { nom: "PERDREAUVILLE", codePostal: "78", zone: "C" },
  { nom: "PERTHES", codePostal: "77", zone: "C" },
  { nom: "PEZARCHES", codePostal: "77", zone: "C" },
  { nom: "PIERRE LEVEE", codePostal: "77", zone: "C" },
  { nom: "PLESSIS FEU AUSSOUX", codePostal: "77", zone: "C" },
  { nom: "PLESSIS PLACY", codePostal: "77", zone: "C" },
  { nom: "PLESSIS ST BENOIST", codePostal: "91", zone: "C" },
  { nom: "POIGNY", codePostal: "77", zone: "C" },
  { nom: "POIGNY LA FORET", codePostal: "78", zone: "C" },
  { nom: "POLIGNY", codePostal: "77", zone: "C" },
  { nom: "POMMEUSE", codePostal: "77", zone: "C" },
  { nom: "PONTHEVRARD", codePostal: "78", zone: "C" },
  { nom: "PORCHEVILLE", codePostal: "78", zone: "C" },
  { nom: "PORT VILLEZ", codePostal: "78", zone: "C" },
  { nom: "PRINGY", codePostal: "77", zone: "C" },
  { nom: "PROVINS", codePostal: "77", zone: "C" },
  { nom: "PRUNAY EN YVELINES", codePostal: "78", zone: "C" },
  { nom: "PRUNAY LE TEMPLE", codePostal: "78", zone: "C" },
  { nom: "PRUNAY SUR ESSONNE", codePostal: "91", zone: "C" },
  { nom: "PUISELET LE MARAIS", codePostal: "91", zone: "C" },
  { nom: "PUISIEUX", codePostal: "77", zone: "C" },
  { nom: "PUSSAY", codePostal: "91", zone: "C" },
  { nom: "QUIERS", codePostal: "77", zone: "C" },
  { nom: "RAIZEUX", codePostal: "78", zone: "C" },
  { nom: "RAMBOUILLET", codePostal: "78", zone: "C" },
  { nom: "RAMPILLON", codePostal: "77", zone: "C" },
  { nom: "REAU", codePostal: "77", zone: "C" },
  { nom: "REBAIS", codePostal: "77", zone: "C" },
  { nom: "RECLOSES", codePostal: "77", zone: "C" },
  { nom: "REMAUVILLE", codePostal: "77", zone: "C" },
  { nom: "RENNEMOULIN", codePostal: "78", zone: "C" },
  { nom: "REUIL EN BRIE", codePostal: "77", zone: "C" },
  { nom: "RICHARVILLE", codePostal: "91", zone: "C" },
  { nom: "RICHEBOURG", codePostal: "78", zone: "C" },
  { nom: "ROCHEFORT EN YVELINES", codePostal: "78", zone: "C" },
  { nom: "ROCQUENCOURT", codePostal: "78", zone: "C" },
  { nom: "ROINVILLE", codePostal: "91", zone: "C" },
  { nom: "ROINVILLIERS", codePostal: "91", zone: "C" },
  { nom: "ROLLEBOISE", codePostal: "78", zone: "C" },
  { nom: "ROSAY", codePostal: "78", zone: "C" },
  { nom: "ROSNY SUR SEINE", codePostal: "78", zone: "C" },
  { nom: "ROUILLY", codePostal: "77", zone: "C" },
  { nom: "ROZAY EN BRIE", codePostal: "77", zone: "C" },
  { nom: "RUBELLES", codePostal: "77", zone: "C" },
  { nom: "RUMONT", codePostal: "77", zone: "C" },
  { nom: "RUPEREUX", codePostal: "77", zone: "C" },
  { nom: "SAACY SUR MARNE", codePostal: "77", zone: "C" },
  { nom: "SABLONNIERES", codePostal: "77", zone: "C" },
  { nom: "SACLAS", codePostal: "91", zone: "C" },
  { nom: "SAGY", codePostal: "95", zone: "C" },
  { nom: "SAILLY", codePostal: "78", zone: "C" },
  { nom: "SAINTE COLOMBE", codePostal: "77", zone: "C" },
  { nom: "SAINTS", codePostal: "77", zone: "C" },
  { nom: "SALINS", codePostal: "77", zone: "C" },
  { nom: "SAMMERON", codePostal: "77", zone: "C" },
  { nom: "SAMOIS SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "SAMOREAU", codePostal: "77", zone: "C" },
  { nom: "SANCY", codePostal: "77", zone: "C" },
  { nom: "SANCY LES PROVINS", codePostal: "77", zone: "C" },
  { nom: "SAULX MARCHAIS", codePostal: "78", zone: "C" },
  { nom: "SAVIGNY LE TEMPLE", codePostal: "77", zone: "C" },
  { nom: "SAVINS", codePostal: "77", zone: "C" },
  { nom: "SEINE PORT", codePostal: "77", zone: "C" },
  { nom: "SENLISSE", codePostal: "78", zone: "C" },
  { nom: "SEPT SORTS", codePostal: "77", zone: "C" },
  { nom: "SEPTEUIL", codePostal: "78", zone: "C" },
  { nom: "SERAINCOURT", codePostal: "95", zone: "C" },
  { nom: "SERMAISE", codePostal: "91", zone: "C" },
  { nom: "SIGNY SIGNETS", codePostal: "77", zone: "C" },
  { nom: "SIGY", codePostal: "77", zone: "C" },
  { nom: "SIVRY COURTRY", codePostal: "77", zone: "C" },
  { nom: "SOGNOLLES EN MONTOIS", codePostal: "77", zone: "C" },
  { nom: "SOIGNOLLES EN BRIE", codePostal: "77", zone: "C" },
  { nom: "SOINDRES", codePostal: "78", zone: "C" },
  { nom: "SOISY BOUY", codePostal: "77", zone: "C" },
  { nom: "SOISY SUR ECOLE", codePostal: "91", zone: "C" },
  { nom: "SOLERS", codePostal: "77", zone: "C" },
  { nom: "SONCHAMP", codePostal: "78", zone: "C" },
  { nom: "SOUPPES SUR LOING", codePostal: "77", zone: "C" },
  { nom: "SOURDUN", codePostal: "77", zone: "C" },
  { nom: "ST ANGE LE VIEL", codePostal: "77", zone: "C" },
  { nom: "ST ARNOULT EN YVELINES", codePostal: "78", zone: "C" },
  { nom: "ST AUGUSTIN", codePostal: "77", zone: "C" },
  { nom: "ST BARTHELEMY", codePostal: "77", zone: "C" },
  { nom: "ST BRICE", codePostal: "77", zone: "C" },
  { nom: "ST CHERON", codePostal: "91", zone: "C" },
  { nom: "ST COME", codePostal: "78", zone: "C" },
  { nom: "ST CYR EN ARTHIES", codePostal: "95", zone: "C" },
  { nom: "ST CYR LA RIVIERE", codePostal: "91", zone: "C" },
  { nom: "ST CYR SOUS DOURDAN", codePostal: "91", zone: "C" },
  { nom: "ST CYR SUR MORIN", codePostal: "77", zone: "C" },
  { nom: "ST DENIS LES REBAIS", codePostal: "77", zone: "C" },
  { nom: "ST ESCOBILLE", codePostal: "91", zone: "C" },
  { nom: "ST FARGEAU PONTHIERRY", codePostal: "77", zone: "C" },
  { nom: "ST FORGET", codePostal: "78", zone: "C" },
  { nom: "ST GERMAIN DE LA GRANGE", codePostal: "78", zone: "C" },
  { nom: "ST GERMAIN LAVAL", codePostal: "77", zone: "C" },
  { nom: "ST GERMAIN LAXIS", codePostal: "77", zone: "C" },
  { nom: "ST GERMAIN SOUS DOUE", codePostal: "77", zone: "C" },
  { nom: "ST GERMAIN SUR ECOLE", codePostal: "77", zone: "C" },
  { nom: "ST GERMAIN SUR MORIN", codePostal: "77", zone: "C" },
  { nom: "ST GERVAIS", codePostal: "95", zone: "C" },
  { nom: "ST HILAIRE", codePostal: "91", zone: "C" },
  { nom: "ST HILARION", codePostal: "78", zone: "C" },
  { nom: "ST HILLIERS", codePostal: "77", zone: "C" },
  { nom: "ST ILLIERS LA VILLE", codePostal: "78", zone: "C" },
  { nom: "ST ILLIERS LE BOIS", codePostal: "78", zone: "C" },
  { nom: "ST JEAN DE BEAUREGARD", codePostal: "91", zone: "C" },
  { nom: "ST JEAN LES DEUX JUMEAUX", codePostal: "77", zone: "C" },
  { nom: "ST JUST EN BRIE", codePostal: "77", zone: "C" },
  { nom: "ST LAMBERT", codePostal: "78", zone: "C" },
  { nom: "ST LEGER EN YVELINES", codePostal: "78", zone: "C" },
  { nom: "ST LOUP DE NAUD", codePostal: "77", zone: "C" },
  { nom: "ST MAMMES", codePostal: "77", zone: "C" },
  { nom: "ST MARS VIEUX MAISONS", codePostal: "77", zone: "C" },
  { nom: "ST MARTIN DE BRETHENCOURT", codePostal: "78", zone: "C" },
  { nom: "ST MARTIN DES CHAMPS", codePostal: "77", zone: "C" },
  { nom: "ST MARTIN EN BIERE", codePostal: "77", zone: "C" },
  { nom: "ST MARTIN LA GARENNE", codePostal: "78", zone: "C" },
  { nom: "ST MAURICE MONTCOURONNE", codePostal: "91", zone: "C" },
  { nom: "ST MERY", codePostal: "77", zone: "C" },
  { nom: "ST OUEN EN BRIE", codePostal: "77", zone: "C" },
  { nom: "ST OUEN SUR MORIN", codePostal: "77", zone: "C" },
  { nom: "ST PIERRE LES NEMOURS", codePostal: "77", zone: "C" },
  { nom: "ST REMY DE LA VANNE", codePostal: "77", zone: "C" },
  { nom: "ST REMY L'HONORE", codePostal: "78", zone: "C" },
  { nom: "ST REMY LES CHEVREUSES", codePostal: "78", zone: "C" },
  { nom: "ST SAUVEUR LES BRAY", codePostal: "77", zone: "C" },
  { nom: "ST SAUVEUR SUR ECOLE", codePostal: "77", zone: "C" },
  { nom: "ST SIMEON", codePostal: "77", zone: "C" },
  { nom: "ST SULPICE DE FAVIERES", codePostal: "91", zone: "C" },
  { nom: "ST VRAIN", codePostal: "91", zone: "C" },
  { nom: "ST YON", codePostal: "91", zone: "C" },
  { nom: "STE AULDE", codePostal: "77", zone: "C" },
  { nom: "STE MESME", codePostal: "78", zone: "C" },
  { nom: "TACOIGNIERES", codePostal: "78", zone: "C" },
  { nom: "TANCROU", codePostal: "77", zone: "C" },
  { nom: "TESSANCOURT SUR AUBETTE", codePostal: "78", zone: "C" },
  { nom: "THEMERICOURT", codePostal: "95", zone: "C" },
  { nom: "THENISY", codePostal: "77", zone: "C" },
  { nom: "THEUVILLE", codePostal: "95", zone: "C" },
  { nom: "THIVERVAL GRIGNON", codePostal: "78", zone: "C" },
  { nom: "THOIRY", codePostal: "78", zone: "C" },
  { nom: "THOMERY", codePostal: "77", zone: "C" },
  { nom: "THOURY FEROTTES", codePostal: "77", zone: "C" },
  { nom: "TIGEAUX", codePostal: "77", zone: "C" },
  { nom: "TILLY", codePostal: "78", zone: "C" },
  { nom: "TOMBE", codePostal: "77", zone: "C" },
  { nom: "TORFOU", codePostal: "91", zone: "C" },
  { nom: "TOUQUIN", codePostal: "77", zone: "C" },
  { nom: "TOUSSON", codePostal: "77", zone: "C" },
  { nom: "TRETOIRE", codePostal: "77", zone: "C" },
  { nom: "TREUZY LEVELAY", codePostal: "77", zone: "C" },
  { nom: "TROCY EN MULTIEN", codePostal: "77", zone: "C" },
  { nom: "URY", codePostal: "77", zone: "C" },
  { nom: "USSY SUR MARNE", codePostal: "77", zone: "C" },
  { nom: "VALENCE EN BRIE", codePostal: "77", zone: "C" },
  { nom: "VALLANGOUJARD", codePostal: "95", zone: "C" },
  { nom: "VALPUISEAUX", codePostal: "91", zone: "C" },
  { nom: "VANVILLE", codePostal: "77", zone: "C" },
  { nom: "VARENNES SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "VAUCOURTOIS", codePostal: "77", zone: "C" },
  { nom: "VAUDOUE", codePostal: "77", zone: "C" },
  { nom: "VAUDOY EN BRIE", codePostal: "77", zone: "C" },
  { nom: "VAUGRIGNEUSE", codePostal: "91", zone: "C" },
  { nom: "VAUX LE PENIL", codePostal: "77", zone: "C" },
  { nom: "VAUX SUR LUNAIN", codePostal: "77", zone: "C" },
  { nom: "VAUX SUR SEINE", codePostal: "78", zone: "C" },
  { nom: "VAYRES SUR ESSONNE", codePostal: "91", zone: "C" },
  { nom: "VENDREST", codePostal: "77", zone: "C" },
  { nom: "VENEUX LES SABLONS", codePostal: "77", zone: "C" },
  { nom: "VERDELOT", codePostal: "77", zone: "C" },
  { nom: "VERNEUIL L'ETANG", codePostal: "77", zone: "C" },
  { nom: "VERNOU LA CELLE SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "VERNOUILLET", codePostal: "78", zone: "C" },
  { nom: "VERT", codePostal: "78", zone: "C" },
  { nom: "VERT LE GRAND", codePostal: "91", zone: "C" },
  { nom: "VERT LE PETIT", codePostal: "91", zone: "C" },
  { nom: "VERT ST DENIS", codePostal: "77", zone: "C" },
  { nom: "VICQ", codePostal: "78", zone: "C" },
  { nom: "VIDELLES", codePostal: "91", zone: "C" },
  { nom: "VIEILLE EGLISE EN YVELINES", codePostal: "78", zone: "C" },
  { nom: "VIENNE EN ARTHIES", codePostal: "95", zone: "C" },
  { nom: "VIEUX CHAMPAGNE", codePostal: "77", zone: "C" },
  { nom: "VILLE SAINT JACQUES", codePostal: "77", zone: "C" },
  { nom: "VILLEBEON", codePostal: "77", zone: "C" },
  { nom: "VILLECERF", codePostal: "77", zone: "C" },
  { nom: "VILLEMARECHAL", codePostal: "77", zone: "C" },
  { nom: "VILLEMER", codePostal: "77", zone: "C" },
  { nom: "VILLENAUXE LA PETITE", codePostal: "77", zone: "C" },
  { nom: "VILLENEUVE LE COMTE", codePostal: "77", zone: "C" },
  { nom: "VILLENEUVE LES BORDES", codePostal: "77", zone: "C" },
  { nom: "VILLENEUVE ST DENIS", codePostal: "77", zone: "C" },
  { nom: "VILLENEUVE SUR AUVERS", codePostal: "91", zone: "C" },
  { nom: "VILLENEUVE SUR BELLOT", codePostal: "77", zone: "C" },
  { nom: "VILLETTE", codePostal: "78", zone: "C" },
  { nom: "VILLIERS EN BIERE", codePostal: "77", zone: "C" },
  { nom: "VILLIERS LE MAHIEU", codePostal: "78", zone: "C" },
  { nom: "VILLIERS SOUS GREZ", codePostal: "77", zone: "C" },
  { nom: "VILLIERS ST GEORGES", codePostal: "77", zone: "C" },
  { nom: "VILLIERS SUR MORIN", codePostal: "77", zone: "C" },
  { nom: "VILLIERS SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "VILLUIS", codePostal: "77", zone: "C" },
  { nom: "VIMPELLES", codePostal: "77", zone: "C" },
  { nom: "VINCY MANŒUVRE", codePostal: "77", zone: "C" },
  { nom: "VOINSLES", codePostal: "77", zone: "C" },
  { nom: "VOISENON", codePostal: "77", zone: "C" },
  { nom: "VOULANGIS", codePostal: "77", zone: "C" },
  { nom: "VOULTON", codePostal: "77", zone: "C" },
  { nom: "VOULX", codePostal: "77", zone: "C" },
  { nom: "VULAINES LES PROVINS", codePostal: "77", zone: "C" },
  { nom: "VULAINES SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "WY DIT JOLI VILLAGE", codePostal: "95", zone: "C" },
];

// Grille tarifaire Express RP par zone et par véhicule
export const tarifsExpressRP = {
  break: {
    A: 45,
    B: 50,
    C: 55,
    D: 60
  },
  fourgon: {
    A: 65,
    B: 75,
    C: 85,
    D: 95
  },
  gv20m3: {
    A: 85,
    B: 100,
    C: 115,
    D: 130
  },
  porteur: {
    A: 120,
    B: 140,
    C: 160,
    D: 180
  },
  semi: {
    A: 180,
    B: 210,
    C: 240,
    D: 270
  }
};

// Fonction pour obtenir la zone d'une ville
export function getZoneExpressRP(villeNom: string): 'A' | 'B' | 'C' | 'D' | null {
  if (!villeNom) return null;
  
  // Extraire le nom de la ville de l'adresse complète (même logique que isVilleExpressRP)
  const matchCodePostalVille = villeNom.match(/\b(\d{5})\s+([^,]+)/);
  let villeExtraite = villeNom;
  
  if (matchCodePostalVille) {
    villeExtraite = matchCodePostalVille[2].trim();
  } else {
    const parts = villeNom.split(',');
    if (parts.length >= 2) {
      const possibleVille = parts[parts.length - 2] || parts[0];
      villeExtraite = possibleVille.replace(/\b\d{5}\b/g, '').trim();
    }
  }
  
  const ville = villesExpressRP.find(v => 
    v.nom.toUpperCase() === villeExtraite.toUpperCase()
  );
  return ville ? ville.zone : null;
}

// Fonction pour obtenir le tarif Express RP
export function getTarifExpressRP(vehiculeType: string, zone: 'A' | 'B' | 'C' | 'D'): number | null {
  // Chercher le véhicule dans le tableau
  const tarifVehicle = tarifsExpressRP.find(t => t.vehicle.toLowerCase() === vehiculeType.toLowerCase());
  if (!tarifVehicle) return null;
  
  return tarifVehicle.prices[zone] || null;
}

// Fonction pour vérifier si une ville est éligible à l'Express RP
export function isVilleExpressRP(villeNom: string): boolean {
  if (!villeNom) return false;
  
  // Extraire le nom de la ville de l'adresse complète
  // Format possible : "Aéroport d'Orly, 94390 Orly, France" → "Orly"
  // ou "75001 Paris, France" → "Paris"
  // ou "Orly" → "Orly"
  
  // Essayer d'extraire le code postal et la ville
  const matchCodePostalVille = villeNom.match(/\b(\d{5})\s+([^,]+)/);
  let villeExtraite = villeNom;
  
  if (matchCodePostalVille) {
    // Format "94390 Orly" → "Orly"
    villeExtraite = matchCodePostalVille[2].trim();
  } else {
    // Chercher la ville après la première virgule mais avant la dernière (qui contient souvent le pays)
    const parts = villeNom.split(',');
    if (parts.length >= 2) {
      // Prendre l'avant-dernière partie qui contient généralement la ville
      const possibleVille = parts[parts.length - 2] || parts[0];
      // Retirer le code postal s'il est présent
      villeExtraite = possibleVille.replace(/\b\d{5}\b/g, '').trim();
    }
  }
  
  return villesExpressRP.some(v => 
    v.nom.toUpperCase() === villeExtraite.toUpperCase()
  );
}
