// Zones Express Région Parisienne
// Zone A : 0-30 km
// Zone B : 30-50 km  
// Zone C : 50-70 km
// Zone D : 70+ km

export interface VilleExpressRP {
  nom: string;
  codePostal: string;
  zone: 'A' | 'B' | 'C' | 'D';
}

// Liste des villes par zone
export const villesExpressRP: VilleExpressRP[] = [
  // Zone A
  { nom: "ABLON SUR SEINE", codePostal: "94", zone: "A" },
  { nom: "ACHERES", codePostal: "78", zone: "A" },
  { nom: "ADAINVILLE", codePostal: "78", zone: "A" },
  { nom: "AINCOURT", codePostal: "95", zone: "A" },
  { nom: "ALFORTVILLE", codePostal: "94", zone: "A" },
  { nom: "ANDILLY", codePostal: "95", zone: "A" },
  { nom: "ANDRESY", codePostal: "78", zone: "A" },
  { nom: "ANNET SUR MARNE", codePostal: "77", zone: "A" },
  { nom: "ANTONY", codePostal: "92", zone: "A" },
  { nom: "ARCUEIL", codePostal: "94", zone: "A" },
  { nom: "ARGENTEUIL", codePostal: "95", zone: "A" },
  { nom: "ARNOUVILLE", codePostal: "95", zone: "A" },
  { nom: "ARNOUVILLE LES GONESSES", codePostal: "95", zone: "A" },
  { nom: "ARTHIES", codePostal: "95", zone: "A" },
  { nom: "ASNIERES SUR SEINE", codePostal: "92", zone: "A" },
  { nom: "ASNIERS SUR OISE", codePostal: "95", zone: "A" },
  { nom: "ATHIS MONS", codePostal: "91", zone: "A" },
  { nom: "ATTAINVILLE", codePostal: "95", zone: "A" },
  { nom: "AUBERVILLIERS", codePostal: "93", zone: "A" },
  { nom: "AULNAY SOUS BOIS", codePostal: "93", zone: "A" },
  { nom: "BAGNEUX", codePostal: "92", zone: "A" },
  { nom: "BAGNOLET", codePostal: "93", zone: "A" },
  { nom: "BAILLET EN FRANCE", codePostal: "95", zone: "A" },
  { nom: "BALLANCOURT SUR ESSONNE", codePostal: "91", zone: "A" },
  { nom: "BANTHELU", codePostal: "95", zone: "A" },
  { nom: "BEAUCHAMP", codePostal: "95", zone: "A" },
  { nom: "BEAUMONT SUR OISE", codePostal: "95", zone: "A" },
  
  // Zone B
  { nom: "AIGREMONT", codePostal: "78", zone: "B" },
  { nom: "AMBLEVILLE", codePostal: "95", zone: "B" },
  { nom: "AMENUCOURT", codePostal: "95", zone: "B" },
  { nom: "ARPAJON", codePostal: "91", zone: "B" },
  { nom: "AUVERNAUX", codePostal: "91", zone: "B" },
  { nom: "AUVERS ST GEORGES", codePostal: "91", zone: "B" },
  { nom: "AUVERS SUR OISE", codePostal: "95", zone: "B" },
  { nom: "AVON", codePostal: "77", zone: "B" },
  { nom: "AVRAINVILLE", codePostal: "91", zone: "B" },
  { nom: "BABY", codePostal: "77", zone: "B" },
  { nom: "BAILLY", codePostal: "78", zone: "B" },
  { nom: "BAILLY ROMAINVILLIERS", codePostal: "77", zone: "B" },
  { nom: "BALLAINVILLIERS", codePostal: "91", zone: "B" },
  { nom: "BARCY", codePostal: "77", zone: "B" },
  { nom: "BAZOCHES SUR GUYONNE", codePostal: "78", zone: "B" },
  { nom: "BEAUVOIR", codePostal: "77", zone: "B" },
  { nom: "BELLEFONTAINE", codePostal: "95", zone: "A" },
  { nom: "BELLOY EN FRANCE", codePostal: "95", zone: "A" },
  { nom: "BERNES SUR OISE", codePostal: "95", zone: "B" },
  { nom: "BERVILLE", codePostal: "95", zone: "B" },
  { nom: "BESSANCOURT", codePostal: "95", zone: "A" },
  { nom: "BETHEMONT LA FORET", codePostal: "95", zone: "B" },
  { nom: "BEZONS", codePostal: "95", zone: "A" },
  { nom: "BIEVRES", codePostal: "91", zone: "A" },
  { nom: "BOBIGNY", codePostal: "93", zone: "A" },
  { nom: "BOINVILLIERS", codePostal: "78", zone: "B" },
  { nom: "BOIS COLOMBES", codePostal: "92", zone: "A" },
  { nom: "BOIS D'ARCY", codePostal: "78", zone: "B" },
  { nom: "BOISSETTES", codePostal: "77", zone: "C" },
  { nom: "BOISSISE LA BERTRAND", codePostal: "77", zone: "C" },
  { nom: "BOISSY L'AILLERIE", codePostal: "95", zone: "B" },
  { nom: "BOISSY MAUVOISIN", codePostal: "78", zone: "B" },
  { nom: "BOISSY ST LEGER", codePostal: "94", zone: "A" },
  { nom: "BONDOUFLE", codePostal: "91", zone: "B" },
  { nom: "BONDY", codePostal: "93", zone: "A" },
  { nom: "BONNEUIL EN FRANCE", codePostal: "95", zone: "A" },
  { nom: "BONNEUIL SUR MARNE", codePostal: "94", zone: "A" },
  { nom: "BOUAFLE", codePostal: "78", zone: "B" },
  { nom: "BOUFFEMONT", codePostal: "95", zone: "A" },
  { nom: "BOUGIVAL", codePostal: "78", zone: "B" },
  { nom: "BOULLAY LES TROUX", codePostal: "91", zone: "B" },
  { nom: "BOULOGNE BILLANCOURT", codePostal: "92", zone: "A" },
  { nom: "BOUQUEVAL", codePostal: "95", zone: "B" },
  { nom: "BOURG LA REINE", codePostal: "92", zone: "A" },
  { nom: "BOUSSY ST ANTOINE", codePostal: "91", zone: "B" },
  { nom: "BREANCON", codePostal: "95", zone: "A" },
  { nom: "BRETIGNY SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "BREUILLET", codePostal: "91", zone: "B" },
  { nom: "BREUX JOUY", codePostal: "91", zone: "C" },
  { nom: "BRIE COMTE ROBERT", codePostal: "77", zone: "B" },
  { nom: "BROU SUR CHANTEREINE", codePostal: "77", zone: "A" },
  { nom: "BRUEIL EN VEXIN", codePostal: "78", zone: "B" },
  { nom: "BRUNOY", codePostal: "91", zone: "B" },
  { nom: "BRUYERES LE CHATEL", codePostal: "91", zone: "B" },
  { nom: "BRUYERES SUR OISE", codePostal: "95", zone: "B" },
  { nom: "BRY SUR MARNE", codePostal: "94", zone: "A" },
  { nom: "BUC", codePostal: "78", zone: "B" },
  { nom: "BUHY", codePostal: "95", zone: "B" },
  { nom: "BURES SUR YVETTE", codePostal: "91", zone: "B" },
  { nom: "BUSSY ST GEORGES", codePostal: "77", zone: "A" },
  { nom: "BUSSY ST MARTIN", codePostal: "77", zone: "B" },
  { nom: "BUTRY SUR OISE", codePostal: "95", zone: "A" },
  
  // Zone C
  { nom: "ABBEVILLE LA RIVIERE", codePostal: "91", zone: "C" },
  { nom: "ABLEIGES", codePostal: "95", zone: "C" },
  { nom: "ABLIS", codePostal: "78", zone: "C" },
  { nom: "ACHERES LA FORET", codePostal: "77", zone: "C" },
  { nom: "ALLAINVILLE", codePostal: "78", zone: "C" },
  { nom: "ALLUETS LE ROI", codePostal: "78", zone: "C" },
  { nom: "AMILLIS", codePostal: "77", zone: "C" },
  { nom: "AMPONVILLE", codePostal: "77", zone: "C" },
  { nom: "ANDELU", codePostal: "78", zone: "C" },
  { nom: "ANDREZEL", codePostal: "77", zone: "C" },
  { nom: "ANGERVILLE", codePostal: "91", zone: "C" },
  { nom: "ANGERVILLIERS", codePostal: "91", zone: "C" },
  { nom: "ARBONNE LA FORET", codePostal: "77", zone: "C" },
  { nom: "ARGENTIERES", codePostal: "77", zone: "C" },
  { nom: "ARMENTIERES EN BRIE", codePostal: "77", zone: "C" },
  { nom: "ARNOUVILLE LES MANTES", codePostal: "78", zone: "C" },
  { nom: "ARRANCOURT", codePostal: "91", zone: "C" },
  { nom: "ARRONVILLE", codePostal: "95", zone: "C" },
  { nom: "ARVILLE", codePostal: "77", zone: "C" },
  { nom: "AUBEPIERRE", codePostal: "77", zone: "C" },
  { nom: "AUBERGENVILLE", codePostal: "78", zone: "C" },
  { nom: "AUFFARGIS", codePostal: "78", zone: "C" },
  { nom: "AUFFERVILLE", codePostal: "77", zone: "C" },
  { nom: "AUFFREVILLE BRASSEUIL", codePostal: "78", zone: "C" },
  { nom: "AUGERS EN BRIE", codePostal: "77", zone: "C" },
  { nom: "AULNAY SUR MAULDRE", codePostal: "78", zone: "C" },
  { nom: "AULNOY", codePostal: "77", zone: "C" },
  { nom: "AUTEUIL", codePostal: "78", zone: "C" },
  { nom: "AUTHON LA PLAINE", codePostal: "91", zone: "C" },
  { nom: "AUTOUILLET", codePostal: "78", zone: "C" },
  { nom: "AVERNES", codePostal: "95", zone: "C" },
  { nom: "AVON", codePostal: "77", zone: "C" },
  { nom: "BAGNEAUX SUR LOING", codePostal: "77", zone: "C" },
  { nom: "BANNOST VILLEGAGNON", codePostal: "77", zone: "C" },
  { nom: "BARBEY", codePostal: "77", zone: "C" },
  { nom: "BARBIZON", codePostal: "77", zone: "C" },
  { nom: "BASSEVELLE", codePostal: "77", zone: "C" },
  { nom: "BAULNE", codePostal: "91", zone: "C" },
  { nom: "BAZAINVILLE", codePostal: "78", zone: "C" },
  { nom: "BAZEMONT", codePostal: "78", zone: "C" },
  { nom: "BAZOCHES LES BRAY", codePostal: "77", zone: "C" },
  { nom: "BEAUCHERY SAINT MARTIN", codePostal: "77", zone: "C" },
  { nom: "BEAUMONT DU GATINAIS", codePostal: "77", zone: "C" },
  { nom: "BEAUTHEIL", codePostal: "77", zone: "C" },
  { nom: "BEHOUST", codePostal: "78", zone: "C" },
  { nom: "BELLOT", codePostal: "77", zone: "C" },
  { nom: "BENNECOURT", codePostal: "78", zone: "C" },
  { nom: "BERNAY VILBERT", codePostal: "77", zone: "C" },
  { nom: "BETON BAZOCHES", codePostal: "77", zone: "C" },
  { nom: "BEYNES", codePostal: "78", zone: "C" },
  { nom: "BEZALLES", codePostal: "77", zone: "C" },
  { nom: "BLANDY", codePostal: "77", zone: "C" },
  { nom: "BLARU", codePostal: "78", zone: "C" },
  { nom: "BLENNES", codePostal: "77", zone: "C" },
  { nom: "BOIGNEVILLE", codePostal: "91", zone: "C" },
  { nom: "BOINVILLE EN MANTOIS", codePostal: "78", zone: "C" },
  { nom: "BOINVILLE LE GAILLARD", codePostal: "78", zone: "C" },
  { nom: "BOIS HERPIN", codePostal: "91", zone: "C" },
  { nom: "BOIS LE ROI", codePostal: "77", zone: "C" },
  { nom: "BOISDON", codePostal: "77", zone: "C" },
  { nom: "BOISSETS", codePostal: "78", zone: "C" },
  { nom: "BOISSISE LE ROI", codePostal: "77", zone: "C" },
  { nom: "BOISSY AUX CAILLES", codePostal: "77", zone: "C" },
  { nom: "BOISSY LA RIVIERE", codePostal: "91", zone: "C" },
  { nom: "BOISSY LE CHATEL", codePostal: "77", zone: "C" },
  { nom: "BOISSY LE CUTTE", codePostal: "91", zone: "C" },
  { nom: "BOISSY LE SEC", codePostal: "91", zone: "C" },
  { nom: "BOISSY SANS AVOIR", codePostal: "78", zone: "C" },
  { nom: "BOISSY SOUS ST YON", codePostal: "91", zone: "C" },
  { nom: "BOITRON", codePostal: "77", zone: "C" },
  { nom: "BOMBON", codePostal: "77", zone: "C" },
  { nom: "BONNELLES", codePostal: "78", zone: "C" },
  { nom: "BONNIERES SUR SEINE", codePostal: "78", zone: "C" },
  { nom: "BOUGLIGNY", codePostal: "77", zone: "C" },
  { nom: "BOULANCOURT", codePostal: "77", zone: "C" },
  { nom: "BOULEURS", codePostal: "77", zone: "C" },
  { nom: "BOURAY SUR JUINE", codePostal: "91", zone: "C" },
  { nom: "BOURDONNE", codePostal: "78", zone: "A" },
  { nom: "BOURRON MARLOTTE", codePostal: "77", zone: "C" },
  { nom: "BOUTERVILLIERS", codePostal: "91", zone: "C" },
  { nom: "BOUTIGNY", codePostal: "77", zone: "C" },
  { nom: "BOUTIGNY SUR ESSONNE", codePostal: "91", zone: "C" },
  { nom: "BOUVILLE", codePostal: "91", zone: "C" },
  { nom: "BRANSLES", codePostal: "77", zone: "C" },
  { nom: "BRAY ET LU", codePostal: "95", zone: "B" },
  { nom: "BRAY SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "BREAU", codePostal: "77", zone: "C" },
  { nom: "BREUIL BOIS ROBERT", codePostal: "78", zone: "C" },
  { nom: "BREVAL", codePostal: "78", zone: "C" },
  { nom: "BRIERES LES SCELLES", codePostal: "91", zone: "C" },
  { nom: "BRIGNANCOURT", codePostal: "95", zone: "C" },
  { nom: "BRIIS SOUS FORGES", codePostal: "91", zone: "C" },
  { nom: "BROSSE MONTCEAUX", codePostal: "77", zone: "C" },
  { nom: "BROUY", codePostal: "91", zone: "C" },
  { nom: "BUCHELAY", codePostal: "78", zone: "C" },
  { nom: "BULLION", codePostal: "78", zone: "C" },
  { nom: "BUNO BONNEVAUX", codePostal: "91", zone: "C" },
  { nom: "BURCY", codePostal: "77", zone: "C" },
  { nom: "BUSSIERES", codePostal: "77", zone: "C" },
  { nom: "BUTHIERS", codePostal: "77", zone: "C" },
  { nom: "CACHAN", codePostal: "94", zone: "A" },
  { nom: "CANNES ECLUSE", codePostal: "77", zone: "C" },
  { nom: "CARNETIN", codePostal: "77", zone: "A" },
  { nom: "CARRIERES SOUS POISSY", codePostal: "78", zone: "B" },
  { nom: "CARRIERES SUR SEINE", codePostal: "78", zone: "A" },
  { nom: "CELLE SUR MORIN", codePostal: "77", zone: "C" },
  { nom: "CELY", codePostal: "77", zone: "C" },
  { nom: "CERGY ST CHRISTOPHE", codePostal: "95", zone: "A" },
  { nom: "CERNAY LA VILLE", codePostal: "78", zone: "C" },
  { nom: "CERNEUX", codePostal: "77", zone: "C" },
  { nom: "CERNY", codePostal: "91", zone: "C" },
  { nom: "CESSON", codePostal: "77", zone: "C" },
  { nom: "CESSOY EN MONTOIS", codePostal: "77", zone: "C" },
  { nom: "CHAILLY EN BIERE", codePostal: "77", zone: "C" },
  { nom: "CHAILLY EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CHAINTREAUX", codePostal: "77", zone: "C" },
  { nom: "CHALAUTRE LA GRANDE", codePostal: "77", zone: "C" },
  { nom: "CHALAUTRE LA PETITE", codePostal: "77", zone: "C" },
  { nom: "CHALIFERT", codePostal: "77", zone: "C" },
  { nom: "CHALMAISON", codePostal: "77", zone: "C" },
  { nom: "CHALO ST MARS", codePostal: "91", zone: "C" },
  { nom: "CHALOU MOULINEUX", codePostal: "91", zone: "C" },
  { nom: "CHAMARANDE", codePostal: "91", zone: "C" },
  { nom: "CHAMBOURCY", codePostal: "78", zone: "B" },
  { nom: "CHAMBRY", codePostal: "77", zone: "B" },
  { nom: "CHAMIGNY", codePostal: "77", zone: "C" },
  { nom: "CHAMPAGNE SUR OISE", codePostal: "95", zone: "B" },
  { nom: "CHAMPAGNE SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "CHAMPCENEST", codePostal: "77", zone: "C" },
  { nom: "CHAMPCUEIL", codePostal: "91", zone: "C" },
  { nom: "CHAMPDEUIL", codePostal: "77", zone: "C" },
  { nom: "CHAMPEAUX", codePostal: "77", zone: "C" },
  { nom: "CHAMPIGNY SUR MARNE", codePostal: "94", zone: "A" },
  { nom: "CHAMPLAN", codePostal: "91", zone: "A" },
  { nom: "CHAMPMOTTEUX", codePostal: "91", zone: "C" },
  { nom: "CHAMPS SUR MARNE", codePostal: "77", zone: "A" },
  { nom: "CHANGIS SUR MARNE", codePostal: "77", zone: "C" },
  { nom: "CHANTELOUP EN BRIE", codePostal: "77", zone: "A" },
  { nom: "CHANTELOUP LES VIGNES", codePostal: "78", zone: "B" },
  { nom: "CHAPELLE GAUTHIER", codePostal: "77", zone: "C" },
  { nom: "CHAPELLE IGER", codePostal: "77", zone: "C" },
  { nom: "CHAPELLE LA REINE", codePostal: "77", zone: "C" },
  { nom: "CHAPELLE RABLAIS", codePostal: "77", zone: "C" },
  { nom: "CHAPELLE SAINT SULPICE", codePostal: "77", zone: "C" },
  { nom: "CHAPET", codePostal: "78", zone: "C" },
  { nom: "CHARENTON", codePostal: "94", zone: "A" },
  { nom: "CHARMENTRAY", codePostal: "77", zone: "A" },
  { nom: "CHARMONT", codePostal: "95", zone: "A" },
  { nom: "CHARNY", codePostal: "77", zone: "A" },
  { nom: "CHARS", codePostal: "95", zone: "B" },
  { nom: "CHARTRETTES", codePostal: "77", zone: "C" },
  { nom: "CHARTRONGES", codePostal: "77", zone: "C" },
  { nom: "CHATEAU LANDON", codePostal: "77", zone: "C" },
  { nom: "CHATEAUBLEAU", codePostal: "77", zone: "C" },
  { nom: "CHATEAUFORT", codePostal: "78", zone: "B" },
  { nom: "CHATELET EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CHATENAY EN FRANCE", codePostal: "95", zone: "A" },
  { nom: "CHATENAY MALABRY", codePostal: "92", zone: "A" },
  { nom: "CHATENAY SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "CHATENOY", codePostal: "77", zone: "C" },
  { nom: "CHATIGNONVILLE", codePostal: "91", zone: "C" },
  { nom: "CHATILLON", codePostal: "92", zone: "A" },
  { nom: "CHATILLON LA BORDE", codePostal: "77", zone: "C" },
  { nom: "CHATOU", codePostal: "78", zone: "A" },
  { nom: "CHATRES", codePostal: "77", zone: "C" },
  { nom: "CHAUCONIN NEUFMONTIERS", codePostal: "77", zone: "B" },
  { nom: "CHAUFFOUR LES ETRECHY", codePostal: "91", zone: "B" },
  { nom: "CHAUFFRY", codePostal: "77", zone: "C" },
  { nom: "CHAUFOUR LES BONNIERES", codePostal: "78", zone: "C" },
  { nom: "CHAUMES EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CHAUMONTEL", codePostal: "95", zone: "A" },
  { nom: "CHAUSSY", codePostal: "95", zone: "B" },
  { nom: "CHAUVRY", codePostal: "95", zone: "A" },
  { nom: "CHAVENAY", codePostal: "78", zone: "B" },
  { nom: "CHAVILLE", codePostal: "92", zone: "A" },
  { nom: "CHELLES", codePostal: "77", zone: "A" },
  { nom: "CHENNEVIERES LES LOUVRES", codePostal: "95", zone: "A" },
  { nom: "CHENNEVIERES SUR MARNE", codePostal: "94", zone: "A" },
  { nom: "CHENOISE", codePostal: "77", zone: "C" },
  { nom: "CHENOU", codePostal: "77", zone: "C" },
  { nom: "CHEPTAINVILLE", codePostal: "91", zone: "B" },
  { nom: "CHERENCE", codePostal: "95", zone: "C" },
  { nom: "CHESSY", codePostal: "77", zone: "B" },
  { nom: "CHEVANNES", codePostal: "91", zone: "C" },
  { nom: "CHEVILLY LA RUE", codePostal: "94", zone: "A" },
  { nom: "CHEVRAINVILLIERS", codePostal: "77", zone: "C" },
  { nom: "CHEVREUSE", codePostal: "78", zone: "C" },
  { nom: "CHEVRU", codePostal: "77", zone: "C" },
  { nom: "CHEVRY COSSIGNY", codePostal: "77", zone: "B" },
  { nom: "CHEVRY EN SEREINE", codePostal: "77", zone: "C" },
  { nom: "CHILLY MAZARIN", codePostal: "91", zone: "A" },
  { nom: "CHOISEL", codePostal: "78", zone: "C" },
  { nom: "CHOISY EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CHOISY LE ROI", codePostal: "94", zone: "A" },
  { nom: "CITRY", codePostal: "77", zone: "C" },
  { nom: "CIVRY LA FORET", codePostal: "78", zone: "C" },
  { nom: "CLAIREFONTAINE EN YVELINES", codePostal: "78", zone: "B" },
  { nom: "CLAMART", codePostal: "92", zone: "A" },
  { nom: "CLAYE SOUILLY", codePostal: "77", zone: "A" },
  { nom: "CLERY EN VEXIN", codePostal: "95", zone: "A" },
  { nom: "CLICHY SOUS BOIS", codePostal: "93", zone: "A" },
  { nom: "CLICHY SUR SEINE", codePostal: "92", zone: "A" },
  { nom: "CLOS FONTAINE", codePostal: "77", zone: "C" },
  { nom: "COCHEREL", codePostal: "77", zone: "C" },
  { nom: "COIGNIERES", codePostal: "78", zone: "B" },
  { nom: "COLLEGIEN", codePostal: "77", zone: "A" },
  { nom: "COLOMBES", codePostal: "92", zone: "A" },
  { nom: "COMBS LA VILLE", codePostal: "77", zone: "B" },
  { nom: "COMMENY", codePostal: "95", zone: "C" },
  { nom: "COMPANS", codePostal: "77", zone: "A" },
  { nom: "CONCHES", codePostal: "77", zone: "A" },
  { nom: "CONDE STE LIBIAIRE", codePostal: "77", zone: "C" },
  { nom: "CONDE SUR VESGRE", codePostal: "78", zone: "A" },
  { nom: "CONDECOURT", codePostal: "95", zone: "C" },
  { nom: "CONFLANS STE HONORINE", codePostal: "78", zone: "A" },
  { nom: "CONGERVILLE", codePostal: "91", zone: "C" },
  { nom: "CONGIS SUR THEROUANNE", codePostal: "77", zone: "C" },
  { nom: "CORBEIL ESSONNES", codePostal: "91", zone: "B" },
  { nom: "CORBREUSE", codePostal: "91", zone: "C" },
  { nom: "CORMEILLES EN PARISIS", codePostal: "95", zone: "A" },
  { nom: "CORMEILLES EN VEXIN", codePostal: "95", zone: "B" },
  { nom: "COUBERT", codePostal: "77", zone: "B" },
  { nom: "COUBRON", codePostal: "93", zone: "A" },
  { nom: "COUILLY PONT AUX DAMES", codePostal: "77", zone: "C" },
  { nom: "COULOMBS EN VALOIS", codePostal: "77", zone: "C" },
  { nom: "COULOMMES", codePostal: "77", zone: "C" },
  { nom: "COULOMMIERS", codePostal: "77", zone: "C" },
  { nom: "COUPVRAY", codePostal: "77", zone: "B" },
  { nom: "COURANCES", codePostal: "91", zone: "B" },
  { nom: "COURBEVOIE", codePostal: "92", zone: "A" },
  { nom: "COURCELLES EN BASSEE", codePostal: "77", zone: "C" },
  { nom: "COURCELLES SUR VIOSNE", codePostal: "95", zone: "B" },
  { nom: "COURCHAMP", codePostal: "77", zone: "C" },
  { nom: "COURCOURONNES", codePostal: "91", zone: "B" },
  { nom: "COURDIMANCHE", codePostal: "95", zone: "A" },
  { nom: "COURDIMANCHE SUR ESSONNE", codePostal: "91", zone: "C" },
  { nom: "COURGENT", codePostal: "78", zone: "C" },
  { nom: "COURPALAY", codePostal: "77", zone: "C" },
  { nom: "COURQUETAINE", codePostal: "77", zone: "C" },
  { nom: "COURSON MONTELOUP", codePostal: "91", zone: "C" },
  { nom: "COURTABOEUF", codePostal: "91", zone: "B" },
  { nom: "COURTACON", codePostal: "77", zone: "C" },
  { nom: "COURTOMER", codePostal: "77", zone: "C" },
  { nom: "COURTRY", codePostal: "77", zone: "A" },
  { nom: "COUTENCON", codePostal: "77", zone: "C" },
  { nom: "COUTEVROULT", codePostal: "77", zone: "C" },
  { nom: "CRAVENT", codePostal: "78", zone: "C" },
  { nom: "CRECY LA CHAPELLE", codePostal: "77", zone: "C" },
  { nom: "CREGY LES MEAUX", codePostal: "77", zone: "B" },
  { nom: "CRESPIERES", codePostal: "78", zone: "C" },
  { nom: "CRETEIL", codePostal: "94", zone: "A" },
  { nom: "CREVECOEUR EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CRISENOY", codePostal: "77", zone: "C" },
  { nom: "CROISSY BEAUBOURG", codePostal: "77", zone: "A" },
  { nom: "CROISSY SUR SEINE", codePostal: "78", zone: "A" },
  { nom: "CROIX EN BRIE", codePostal: "77", zone: "C" },
  { nom: "CROSNE", codePostal: "91", zone: "A" },
  { nom: "CROUY SUR OURCQ", codePostal: "77", zone: "C" },
  { nom: "CUCHARMOY", codePostal: "77", zone: "C" },
  { nom: "CUISY", codePostal: "77", zone: "B" },
  { nom: "D'HUISON LONGUEVILLE", codePostal: "91", zone: "C" },
  { nom: "DAGNY", codePostal: "77", zone: "C" },
  { nom: "DAMMARIE LES LYS", codePostal: "77", zone: "C" },
  { nom: "DAMMARTIN EN GOELE", codePostal: "77", zone: "A" },
  { nom: "DAMMARTIN EN SERVE", codePostal: "78", zone: "A" },
  { nom: "DAMMARTIN SUR TIGEAUX", codePostal: "77", zone: "C" },
  { nom: "DAMPIERRE EN YVELINES", codePostal: "78", zone: "C" },
  { nom: "DAMPMART", codePostal: "77", zone: "A" },
  { nom: "DANNEMARIE", codePostal: "78", zone: "C" },
  { nom: "DANNEMOIS", codePostal: "91", zone: "C" },
  { nom: "DARVAULT", codePostal: "77", zone: "C" },
  { nom: "DAVRON", codePostal: "78", zone: "C" },
  { nom: "DEUIL LA BARRE", codePostal: "95", zone: "A" },
  { nom: "DHUISY", codePostal: "77", zone: "C" },
  { nom: "DIANT", codePostal: "77", zone: "C" },
  { nom: "DOMONT", codePostal: "95", zone: "A" },
  { nom: "DONNEMARIE DONTILLY", codePostal: "77", zone: "C" },
  { nom: "DORMELLES", codePostal: "77", zone: "C" },
  { nom: "DOUE", codePostal: "77", zone: "B" },
  { nom: "DOURDAN", codePostal: "91", zone: "C" },
  { nom: "DOUY LA RAMEE", codePostal: "77", zone: "C" },
  { nom: "DRANCY", codePostal: "93", zone: "A" },
  { nom: "DRAVEIL", codePostal: "91", zone: "A" },
  { nom: "DROCOURT", codePostal: "78", zone: "B" },
  { nom: "DUGNY", codePostal: "93", zone: "A" },
  { nom: "EAUBONNE", codePostal: "95", zone: "A" },
  { nom: "ECHARCON", codePostal: "91", zone: "C" },
  { nom: "ECHOUBOULAINS", codePostal: "77", zone: "C" },
  { nom: "ECOUEN", codePostal: "95", zone: "A" },
  { nom: "ECQUEVILLY", codePostal: "78", zone: "B" },
  { nom: "ECRENNES", codePostal: "77", zone: "C" },
  { nom: "ECUELLES", codePostal: "77", zone: "C" },
  { nom: "EGLIGNY", codePostal: "77", zone: "C" },
  { nom: "EGLY", codePostal: "91", zone: "C" },
  { nom: "EGREVILLE", codePostal: "77", zone: "C" },
  { nom: "ELANCOURT", codePostal: "78", zone: "B" },
  { nom: "EMANCE", codePostal: "78", zone: "B" },
  { nom: "EMERAINVILLE", codePostal: "77", zone: "A" },
  { nom: "ENGHIEN LES BAINS", codePostal: "95", zone: "A" },
  { nom: "ENNERY", codePostal: "95", zone: "A" },
  { nom: "EPIAIS LES LOUVRES", codePostal: "95", zone: "A" },
  { nom: "EPIAIS RHUS", codePostal: "95", zone: "B" },
  { nom: "EPINAY CHAMPLATREUX", codePostal: "95", zone: "A" },
  { nom: "EPINAY SOUS SENART", codePostal: "91", zone: "A" },
  { nom: "EPINAY SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "EPINAY SUR SEINE", codePostal: "93", zone: "A" },
  { nom: "EPISY", codePostal: "77", zone: "C" },
  { nom: "EPONE", codePostal: "78", zone: "C" },
  { nom: "ERAGNY", codePostal: "95", zone: "A" },
  { nom: "ERMONT", codePostal: "95", zone: "A" },
  { nom: "ESBLY", codePostal: "77", zone: "B" },
  { nom: "ESMANS", codePostal: "77", zone: "C" },
  { nom: "ESTOUCHES", codePostal: "91", zone: "C" },
  { nom: "ETAMPES", codePostal: "91", zone: "C" },
  { nom: "ETIOLLES", codePostal: "91", zone: "B" },
  { nom: "ETRECHY", codePostal: "91", zone: "B" },
  { nom: "ETREPILLY", codePostal: "77", zone: "C" },
  { nom: "EVECQUEMONT", codePostal: "78", zone: "C" },
  { nom: "EVERLY", codePostal: "77", zone: "C" },
  { nom: "EVRY", codePostal: "91", zone: "B" },
  { nom: "EVRY GREGY SUR YERRE", codePostal: "77", zone: "C" },
  { nom: "EZANVILLE", codePostal: "95", zone: "A" },
  { nom: "FAREMOUTIERS", codePostal: "77", zone: "C" },
  { nom: "FAVIERES", codePostal: "77", zone: "C" },
  { nom: "FAVRIEUX", codePostal: "78", zone: "B" },
  { nom: "FAY LES NEMOURS", codePostal: "77", zone: "C" },
  { nom: "FERICY", codePostal: "77", zone: "C" },
  { nom: "FEROLLES ATTILLY", codePostal: "77", zone: "C" },
  { nom: "FERRIERES EN BRIE", codePostal: "77", zone: "B" },
  { nom: "FERTE GAUCHER", codePostal: "77", zone: "C" },
  { nom: "FERTE SOUS JOUARRE", codePostal: "77", zone: "C" },
  { nom: "FEUCHEROLLES", codePostal: "78", zone: "C" },
  { nom: "FLACOURT", codePostal: "78", zone: "C" },
  { nom: "FLAGY", codePostal: "77", zone: "C" },
  { nom: "FLEURY EN BIERE", codePostal: "77", zone: "C" },
  { nom: "FLEURY MEROGIS", codePostal: "91", zone: "A" },
  { nom: "FLEXANVILLE", codePostal: "78", zone: "C" },
  { nom: "FLINS NEUVE EGLISE", codePostal: "78", zone: "C" },
  { nom: "FLINS SUR SEINE", codePostal: "78", zone: "C" },
  { nom: "FOLLAINVILLE DENNEMONT", codePostal: "78", zone: "C" },
  { nom: "FONTAINE FOURCHES", codePostal: "77", zone: "C" },
  { nom: "FONTAINE LA RIVIERE", codePostal: "91", zone: "C" },
  { nom: "FONTAINE LE PORT", codePostal: "77", zone: "C" },
  { nom: "FONTAINEBLEAU", codePostal: "77", zone: "C" },
  { nom: "FONTAINS", codePostal: "77", zone: "C" },
  { nom: "FONTENAILLES", codePostal: "77", zone: "C" },
  { nom: "FONTENAY AUX ROSES", codePostal: "92", zone: "A" },
  { nom: "FONTENAY EN PARISIS", codePostal: "95", zone: "A" },
  { nom: "FONTENAY LE FLEURY", codePostal: "78", zone: "B" },
  { nom: "FONTENAY LE VICOMTE", codePostal: "91", zone: "B" },
  { nom: "FONTENAY LES BRIIS", codePostal: "91", zone: "C" },
  { nom: "FONTENAY MAUVOISIN", codePostal: "78", zone: "C" },
  { nom: "FONTENAY SOUS BOIS", codePostal: "94", zone: "A" },
  { nom: "FONTENAY ST PERE", codePostal: "78", zone: "B" },
  { nom: "FONTENAY TRESIGNY", codePostal: "77", zone: "B" },
  { nom: "FORFRY", codePostal: "77", zone: "B" },
  { nom: "FORGES", codePostal: "77", zone: "C" },
  { nom: "FORGES LES BAINS", codePostal: "91", zone: "B" },
  { nom: "FOSSES", codePostal: "95", zone: "A" },
  { nom: "FOUJU", codePostal: "77", zone: "C" },
  { nom: "FOURQUEUX", codePostal: "78", zone: "A" },
  { nom: "FRANCONVILLE", codePostal: "95", zone: "A" },
  { nom: "FREMAINVILLE", codePostal: "95", zone: "C" },
  { nom: "FREMECOURT", codePostal: "95", zone: "B" },
  { nom: "FRENEUSE", codePostal: "78", zone: "C" },
  { nom: "FREPILLON", codePostal: "95", zone: "B" },
  { nom: "FRESNES", codePostal: "94", zone: "A" },
  { nom: "FRESNES SUR MARNE", codePostal: "77", zone: "A" },
  { nom: "FRETOY", codePostal: "77", zone: "C" },
  { nom: "FROMONT", codePostal: "77", zone: "C" },
  { nom: "FROUVILLE", codePostal: "95", zone: "A" },
  { nom: "FUBLAINES", codePostal: "77", zone: "B" },
  { nom: "GADANCOURT", codePostal: "95", zone: "C" },
  { nom: "GAGNY", codePostal: "93", zone: "A" },
  { nom: "GAILLON SUR MONTCIENT", codePostal: "78", zone: "C" },
  { nom: "GALLUIS", codePostal: "78", zone: "C" },
  { nom: "GAMBAIS", codePostal: "78", zone: "C" },
  { nom: "GAMBAISEUIL", codePostal: "78", zone: "C" },
  { nom: "GARANCIERES", codePostal: "78", zone: "C" },
  { nom: "GARCHES", codePostal: "92", zone: "A" },
  { nom: "GARENTREVILLE", codePostal: "77", zone: "C" },
  { nom: "GARGENVILLE", codePostal: "78", zone: "C" },
  { nom: "GARGES LES GONESSES", codePostal: "95", zone: "A" },
  { nom: "GASTINS", codePostal: "77", zone: "C" },
  { nom: "GAZERAN", codePostal: "78", zone: "C" },
  { nom: "GENAINVILLE", codePostal: "95", zone: "A" },
  { nom: "GENEVRAYE", codePostal: "77", zone: "C" },
  { nom: "GENICOURT", codePostal: "95", zone: "B" },
  { nom: "GENNEVILLIERS", codePostal: "92", zone: "A" },
  { nom: "GENTILLY", codePostal: "94", zone: "A" },
  { nom: "GERMIGNY L'EVEQUE", codePostal: "77", zone: "B" },
  { nom: "GERMIGNY SOUS COLOMBS", codePostal: "77", zone: "C" },
  { nom: "GESVRES LE CHAPITRE", codePostal: "77", zone: "B" },
  { nom: "GIF SUR YVETTE", codePostal: "91", zone: "B" },
  { nom: "GIREMOUTIERS", codePostal: "77", zone: "C" },
  { nom: "GIRONVILLE", codePostal: "77", zone: "C" },
  { nom: "GIRONVILLE SUR ESSONNE", codePostal: "91", zone: "C" },
  { nom: "GOMETZ LA VILLE", codePostal: "91", zone: "B" },
  { nom: "GOMETZ LE CHATEL", codePostal: "91", zone: "B" },
  { nom: "GOMMECOURT", codePostal: "78", zone: "C" },
  { nom: "GONESSE", codePostal: "95", zone: "A" },
  { nom: "GOUAIX", codePostal: "77", zone: "C" },
  { nom: "GOUPILLIERES", codePostal: "78", zone: "C" },
  { nom: "GOURNAY SUR MARNE", codePostal: "93", zone: "A" },
  { nom: "GOUSSAINVILLE", codePostal: "95", zone: "A" },
  { nom: "GOUSSONVILLE", codePostal: "78", zone: "C" },
  { nom: "GOUVERNES", codePostal: "77", zone: "A" },
  { nom: "GOUZANGREZ", codePostal: "95", zone: "C" },
  { nom: "GRANDCHAMP", codePostal: "78", zone: "A" },
  { nom: "GRANDPUITS BAILLY CARROIS", codePostal: "77", zone: "C" },
  { nom: "GRAVON", codePostal: "77", zone: "C" },
  { nom: "GRESSEY", codePostal: "78", zone: "C" },
  { nom: "GRESSY", codePostal: "77", zone: "A" },
  { nom: "GRETZ ARMAINVILLIERS", codePostal: "77", zone: "B" },
  { nom: "GREZ SUR LOING", codePostal: "77", zone: "C" },
  { nom: "GRIGNY", codePostal: "91", zone: "A" },
  { nom: "GRISY LES PLATRES", codePostal: "95", zone: "B" },
  { nom: "GRISY SUISNES", codePostal: "77", zone: "C" },
  { nom: "GRISY SUR SEINE", codePostal: "77", zone: "C" },
  { nom: "GROSLAY", codePostal: "95", zone: "A" },
  { nom: "GROSROUVRE", codePostal: "78", zone: "C" },
  { nom: "GUERARD", codePostal: "77", zone: "C" },
  { nom: "GUERCHEVILLE", codePostal: "77", zone: "C" },
  { nom: "GUERMANTES", codePostal: "77", zone: "A" },
  { nom: "GUERNES", codePostal: "78", zone: "C" },
  { nom: "GUERVILLE", codePostal: "78", zone: "C" },
  { nom: "GUIBEVILLE", codePostal: "91", zone: "C" },
  { nom: "GUIGNES", codePostal: "77", zone: "C" },
  { nom: "GUIGNEVILLE SUR ESSONNE", codePostal: "91", zone: "C" },
  { nom: "GUILLERVAL", codePostal: "91", zone: "C" },
  { nom: "GUIRY EN VEXIN", codePostal: "95", zone: "C" },
  { nom: "GUITRANCOURT", codePostal: "78", zone: "B" },
  { nom: "GURCY LE CHATEL", codePostal: "77", zone: "C" },
  { nom: "GUYANCOURT", codePostal: "78", zone: "B" },
  { nom: "HARAVILLIERS", codePostal: "95", zone: "B" },
  { nom: "HARDRICOURT", codePostal: "78", zone: "C" },
  { nom: "HARGEVILLE", codePostal: "78", zone: "C" },
  { nom: "HAUTE ISLE", codePostal: "95", zone: "B" },
  { nom: "HAUTE MAISON", codePostal: "77", zone: "C" },
  { nom: "HAUTEFEUILLE", codePostal: "77", zone: "C" },
  { nom: "HEDOUVILLE", codePostal: "95", zone: "A" },
  { nom: "HERBEVILLE", codePostal: "78", zone: "C" },
  { nom: "HERBLAY", codePostal: "95", zone: "A" },
  { nom: "HERICY", codePostal: "77", zone: "C" },
  { nom: "HERME", codePostal: "77", zone: "C" },
  { nom: "HERMERAY", codePostal: "78", zone: "B" },
  { nom: "HEROUVILLE", codePostal: "95", zone: "B" },
  { nom: "HODENT", codePostal: "95", zone: "C" },
  { nom: "HONDEVILLIERS", codePostal: "77", zone: "B" },
  { nom: "HOUDAN", codePostal: "78", zone: "C" },
  { nom: "HOUILLES", codePostal: "78", zone: "A" },
  { nom: "ICHY", codePostal: "77", zone: "C" },
  { nom: "IGNY", codePostal: "91", zone: "A" },
  { nom: "ILE SAINT DENIS", codePostal: "93", zone: "A" },
  { nom: "ISLES LES MELDEUSES", codePostal: "77", zone: "C" },
  { nom: "ISLES LES VILLENOY", codePostal: "77", zone: "B" },
  { nom: "ISSOU", codePostal: "78", zone: "C" },
  { nom: "ISSY LES MOULINEAUX", codePostal: "92", zone: "A" },
  { nom: "ITTEVILLE", codePostal: "91", zone: "C" },
  { nom: "IVERNY", codePostal: "77", zone: "B" },
  { nom: "IVRY SUR SEINE", codePostal: "94", zone: "A" },
  { nom: "JABLINES", codePostal: "77", zone: "A" },
  { nom: "JAGNY SOUS BOIS", codePostal: "95", zone: "B" },
  { nom: "JAIGNES", codePostal: "77", zone: "C" },
  { nom: "JAMBVILLE", codePostal: "78", zone: "C" },
  { nom: "JANVILLE SUR JUINE", codePostal: "91", zone: "C" },
  { nom: "JANVRY", codePostal: "91", zone: "C" },
  { nom: "JAULNES", codePostal: "77", zone: "C" },
  { nom: "JEUFOSSE", codePostal: "78", zone: "C" },
  { nom: "JOINVILLE LE PONT", codePostal: "94", zone: "A" },
  { nom: "JOSSIGNY", codePostal: "77", zone: "A" },
  { nom: "JOUARRE", codePostal: "77", zone: "C" },
  { nom: "JOUARS PONTCHARTRAIN", codePostal: "78", zone: "C" },
  { nom: "JOUY EN JOSAS", codePostal: "78", zone: "B" },
  { nom: "JOUY LE CHATEL", codePostal: "77", zone: "B" },
  { nom: "JOUY MAUVOISIN", codePostal: "78", zone: "C" },
  { nom: "JOUY SUR MORIN", codePostal: "77", zone: "C" },
  { nom: "JUILLY", codePostal: "77", zone: "A" },
  { nom: "JUMEAUVILLE", codePostal: "78", zone: "C" },
  { nom: "JUTIGNY", codePostal: "77", zone: "C" },
  { nom: "JUVISY SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "JUZIERS", codePostal: "78", zone: "C" },
  { nom: "KREMLIN BICETRE", codePostal: "94", zone: "A" },
  { nom: "L'ETANG LA VILLE", codePostal: "78", zone: "C" },
  { nom: "L'HAY LES ROSES", codePostal: "94", zone: "A" },
  { nom: "L'ISLE ADAM", codePostal: "95", zone: "B" },
  { nom: "LA BOISSIERE ECOLE", codePostal: "78", zone: "B" },
  { nom: "LA CELLE LES BORDES", codePostal: "78", zone: "C" },
  { nom: "LA CELLE ST CLOUD", codePostal: "78", zone: "A" },
  { nom: "LA CHAPELLE EN VEXIN", codePostal: "95", zone: "A" },
  { nom: "LA CHAPELLE MOUTILS", codePostal: "77", zone: "C" },
  { nom: "LA COURNEUVE", codePostal: "93", zone: "A" },
  { nom: "LA DEFENSE", codePostal: "92", zone: "A" },
  { nom: "LA FALAISE", codePostal: "78", zone: "C" },
  { nom: "LA FERTE ALAIS", codePostal: "91", zone: "C" },
  { nom: "LA FORET LE ROI", codePostal: "91", zone: "C" },
  { nom: "LA FORET STE CROIX", codePostal: "91", zone: "C" },
  { nom: "LA FRETTE SUR SEINE", codePostal: "95", zone: "A" },
  { nom: "LA GARENNE COLOMBES", codePostal: "92", zone: "A" },
  { nom: "LA GRANDE PAROISSE", codePostal: "77", zone: "C" },
  { nom: "LA HAUTEVILLE", codePostal: "78", zone: "A" },
  { nom: "LA HOUSSAYE EN BRIE", codePostal: "77", zone: "B" },
  { nom: "LA QUEUE EN BRIE", codePostal: "94", zone: "A" },
  { nom: "LA QUEUE LES YVELINES", codePostal: "78", zone: "C" },
  { nom: "LA ROCHE GUYON", codePostal: "95", zone: "B" },
  { nom: "LA ROCHETTE", codePostal: "77", zone: "C" },
  { nom: "LA VARENNE ST HILAIRE", codePostal: "94", zone: "A" },
  { nom: "LA VERRIERE", codePostal: "78", zone: "B" },
  { nom: "LA VILLE DU BOIS", codePostal: "91", zone: "B" },
  { nom: "LA VILLENEUVE EN CHEVRIE", codePostal: "78", zone: "C" },
  { nom: "LABBEVILLE", codePostal: "95", zone: "B" },
  { nom: "LAGNY SUR MARNE", codePostal: "77", zone: "A" },
  { nom: "LAINVILLE", codePostal: "78", zone: "C" },
  { nom: "LARCHANT", codePostal: "77", zone: "C" },
  { nom: "LARDY", codePostal: "91", zone: "C" },
  { nom: "LASSY", codePostal: "95", zone: "A" },
  { nom: "LAVAL EN BRIE", codePostal: "77", zone: "C" },
  { nom: "LE BELLAY EN VEXIN", codePostal: "95", zone: "B" },
  { nom: "LE BLANC MESNIL", codePostal: "93", zone: "A" },
  { nom: "LE BOURGET", codePostal: "93", zone: "A" },
  { nom: "LE CHESNAY", codePostal: "78", zone: "A" },
  { nom: "LE COUDRAY MONTCEAUX", codePostal: "91", zone: "B" },
  { nom: "LE HEAULME", codePostal: "95", zone: "B" },
  { nom: "LE MESNIL AUBRY", codePostal: "95", zone: "B" },
  { nom: "LE MESNIL LE ROI", codePostal: "77", zone: "B" },
  { nom: "LE MESNIL ST DENIS", codePostal: "78", zone: "C" },
  { nom: "LE PECQ", codePostal: "78", zone: "B" },
  { nom: "LE PERCHAY", codePostal: "95", zone: "C" },
  { nom: "LE PERRAY EN YVELINES", codePostal: "78", zone: "C" },
  { nom: "LE PERREUX", codePostal: "94", zone: "A" },
  { nom: "LE PIN", codePostal: "77", zone: "A" },
  { nom: "LE PLESSIS BOUCHARD", codePostal: "95", zone: "A" },
  { nom: "LE PLESSIS GASSOT", codePostal: "95", zone: "B" },
  { nom: "LE PLESSIS LUZARCHES", codePostal: "95", zone: "A" },
  { nom: "LE PLESSIS PATE", codePostal: "91", zone: "A" },
  { nom: "LE PLESSIS ROBINSON", codePostal: "92", zone: "A" },
  { nom: "LE PLESSIS TREVISE", codePostal: "94", zone: "A" },
  { nom: "LE PRE ST GERVAIS", codePostal: "93", zone: "A" },
  { nom: "LE RAINCY", codePostal: "93", zone: "A" },
  { nom: "LE TARTRE GAUDRAN", codePostal: "78", zone: "B" },
  { nom: "LE TERTRE ST DENIS", codePostal: "78", zone: "C" },
  { nom: "LE THILLAY", codePostal: "95", zone: "A" },
  { nom: "LE TREMBLAY SUR MAULDRE", codePostal: "78", zone: "C" },
  { nom: "LE VAL ST GERMAIN", codePostal: "91", zone: "C" },
  { nom: "LE VESINET", codePostal: "78", zone: "A" },
  { nom: "LECHELLE", codePostal: "77", zone: "C" },
  { nom: "LES BREVIAIRES", codePostal: "78", zone: "C" },
  { nom: "LES CHAPELLES BOURBONS", codePostal: "77", zone: "C" },
  { nom: "LES CLAYES SOUS BOIS", codePostal: "78", zone: "C" },
  { nom: "LES ESSARTS LE ROI", codePostal: "78", zone: "C" },
  { nom: "LES GRANGES LE ROI", codePostal: "91", zone: "C" },
  { nom: "LES LILAS", codePostal: "93", zone: "A" },
  { nom: "LES LOGES EN JOSAS", codePostal: "78", zone: "C" },
  { nom: "LES MESNULS", codePostal: "78", zone: "C" },
  { nom: "LES MOLIERES", codePostal: "91", zone: "C" },
  { nom: "LES MUREAUX", codePostal: "78", zone: "C" },
  { nom: "LES ORMES SUR VOULZIE", codePostal: "77", zone: "C" },
  { nom: "LES ULIS", codePostal: "91", zone: "B" },
  { nom: "LESCHEROLLES", codePostal: "77", zone: "C" },
  { nom: "LESCHES", codePostal: "77", zone: "B" },
  { nom: "LESIGNY", codePostal: "77", zone: "B" },
  { nom: "LEUDEVILLE", codePostal: "91", zone: "C" },
  { nom: "LEUDON EN BRIE", codePostal: "77", zone: "C" },
  { nom: "LEUVILLE SUR ORGE", codePostal: "91", zone: "B" },
  { nom: "LEVALLOIS PERRET", codePostal: "92", zone: "A" },
  { nom: "LEVIS ST NOM", codePostal: "78", zone: "C" },
  { nom: "LIEUSAINT", codePostal: "77", zone: "B" },
  { nom: "LIMAY", codePostal: "78", zone: "C" },
  { nom: "LIMEIL BREVANNES", codePostal: "94", zone: "A" },
  { nom: "LIMETZ VILLEZ", codePostal: "78", zone: "C" },
  { nom: "LIMOGES FOURCHES", codePostal: "77", zone: "C" },
  { nom: "LIMOURS", codePostal: "91", zone: "C" },
  { nom: "LINAS", codePostal: "91", zone: "C" },
  { nom: "LISSES", codePostal: "91", zone: "B" },
  { nom: "LISSY", codePostal: "77", zone: "C" },
  { nom: "LIVERDY EN BRIE", codePostal: "77", zone: "C" },
  { nom: "LIVILLIERS", codePostal: "95", zone: "B" },
  { nom: "LIVRY GARGAN", codePostal: "93", zone: "A" },
  { nom: "LIVRY SUR SEINE", codePostal: "77", zone: "B" },
  { nom: "LIZINES", codePostal: "77", zone: "C" },
  { nom: "LIZY SUR OURCQ", codePostal: "77", zone: "C" },
  { nom: "LOGNES", codePostal: "77", zone: "A" },
  { nom: "LOMMOYE", codePostal: "78", zone: "C" },
  { nom: "LONGJUMEAU", codePostal: "91", zone: "A" },
  { nom: "LONGNES", codePostal: "78", zone: "C" },
  { nom: "LONGPERRIER", codePostal: "77", zone: "A" },
  { nom: "LONGPONT SUR ORGE", codePostal: "91", zone: "A" },
  { nom: "LONGUESSE", codePostal: "95", zone: "C" },
  { nom: "LONGUEVILLE", codePostal: "77", zone: "C" },
  { nom: "LONGVILLIERS", codePostal: "78", zone: "C" },
  { nom: "LORREZ LE BOCAGE PREAUX", codePostal: "77", zone: "C" },
  { nom: "LOUAN VILLEGRUIS FONTAINE", codePostal: "77", zone: "C" },
  { nom: "LOUVECIENNES", codePostal: "78", zone: "B" },
  { nom: "LOUVRES", codePostal: "78", zone: "A" },
  { nom: "LUISETAINES", codePostal: "77", zone: "C" },
  { nom: "LUMIGNY NESLES ORMEAUX", codePostal: "77", zone: "C" },
  { nom: "LUZANCY", codePostal: "77", zone: "C" },
  { nom: "LUZARCHES", codePostal: "95", zone: "A" },
  { nom: "MACHAULT", codePostal: "77", zone: "C" },
  { nom: "MADELEINE SUR LOING", codePostal: "77", zone: "C" },
  { nom: "MAFFLIERS", codePostal: "95", zone: "A" },
  { nom: "MAGNANVILLE", codePostal: "78", zone: "C" },
  { nom: "MAGNY EN VEXIN", codePostal: "95", zone: "C" },
  { nom: "MAGNY LE HONGRE", codePostal: "77", zone: "B" },
  { nom: "MAGNY LES HAMEAUX", codePostal: "78", zone: "B" },
  { nom: "MAINCY", codePostal: "77", zone: "C" },
  { nom: "MAISON ROUGE", codePostal: "77", zone: "C" },
  { nom: "MAISONCELL", codePostal: "78", zone: "C" },
  { nom: "MAISONCELLES EN BRIE", codePostal: "77", zone: "C" },
  { nom: "MAISONCELLES EN GATINAIS", codePostal: "77", zone: "C" },
  { nom: "MAISONS ALFORT", codePostal: "94", zone: "A" },
  { nom: "MAISONS LAFFITTE", codePostal: "78", zone: "A" },
  { nom: "MAISSE", codePostal: "91", zone: "C" },
  { nom: "MALAKOFF", codePostal: "92", zone: "A" },
  { nom: "MANDRES LES ROSES", codePostal: "94", zone: "A" },
  { nom: "MANTES LA JOLIE", codePostal: "78", zone: "C" },
  { nom: "MANTES LA VILLE", codePostal: "78", zone: "C" },
  { nom: "MARCHEMORET", codePostal: "77", zone: "A" },
];

// Grille tarifaire Express RP par zone et par véhicule
export const tarifsExpressRP = {
  break: {
    A: 45,
    B: 50,
    C: 55,
    D: 60
  },
  fourgon: {
    A: 65,
    B: 75,
    C: 85,
    D: 95
  },
  gv20m3: {
    A: 85,
    B: 100,
    C: 115,
    D: 130
  },
  porteur: {
    A: 120,
    B: 140,
    C: 160,
    D: 180
  },
  semi: {
    A: 180,
    B: 210,
    C: 240,
    D: 270
  }
};

// Fonction pour obtenir la zone d'une ville
export function getZoneExpressRP(villeNom: string): 'A' | 'B' | 'C' | 'D' | null {
  const ville = villesExpressRP.find(v => 
    v.nom.toUpperCase() === villeNom.toUpperCase()
  );
  return ville ? ville.zone : null;
}

// Fonction pour obtenir le tarif Express RP
export function getTarifExpressRP(vehiculeType: string, zone: 'A' | 'B' | 'C' | 'D'): number | null {
  const tarifsVehicule = tarifsExpressRP[vehiculeType as keyof typeof tarifsExpressRP];
  if (!tarifsVehicule) return null;
  
  return tarifsVehicule[zone] || null;
}

// Fonction pour vérifier si une ville est éligible à l'Express RP
export function isVilleExpressRP(villeNom: string): boolean {
  return villesExpressRP.some(v => 
    v.nom.toUpperCase() === villeNom.toUpperCase()
  );
}